#!/usr/bin/env python3
# Normalized instruction diff: original RIPTIDE.lst vs BCC -S output.
# usage: adiff.py <orig_fn_pattern> <gen.asm> <gen_label_regex>
import re, sys, difflib

MNEM = set('mov cmp push pop call jmp jb jbe ja jae je jne jz jnz jl jle jg jge js jns '
 'jc jnc jo jno jp jnp jcxz loop lea add sub inc dec xor or and shl shr sar sal rol ror '
 'movzx movsx imul idiv div mul cwd cdq nop ret retf leave enter les lds test neg not '
 'xchg adc sbb cbw movs stos lods scas rep repne repe int in out'.split())
ALIAS = {'jz':'je','jnz':'jne','jc':'jb','jnc':'jae','jnb':'jae','jpe':'jp','jpo':'jnp',
         'ret':'retf','sal':'shl'}
# BC3.1 RTL helper names -> BC2.0 equivalents (FPU conversion helpers etc.)
RTL_ALIAS = {'F_FTOL@':'ftol@','F_FTOL':'ftol@','FTOL@':'ftol@'}
SHORTSZ = {'b:':'byte:','w:':'word:','d:':'dword:'}

def build_symtab(lst):      # dseg name -> (offset, size)
    m = {}
    for l in open(lst, errors='replace'):
        mm = re.match(r'^seg2608:([0-9A-Fa-f]+)\s+([A-Za-z_@$][\w@$]*)\s+(db|dw|dd|dt|dq)', l)
        if mm:
            sz = {'db':'byte','dw':'word','dd':'dword'}.get(mm.group(3),'')
            m[mm.group(2)] = (int(mm.group(1),16), sz)
    return m

DSEG_BASE = 0x28260          # seg2608 linear base (orig listing uses linear addrs)
LIN2NAME = {}                # linear addr -> dseg name
_LKS = []
def build_name_at(sym):
    global LIN2NAME, _LKS
    LIN2NAME = {off + DSEG_BASE: nm for nm,(off,sz) in sym.items()
                if not re.match(r'^(?:byte|word|dword|qword|off|unk|loc)_', nm)}
    _LKS = sorted(LIN2NAME)

def num2name(v):
    """data addr (orig=linear, gen=seg2608 offset) -> canonical 'name'/'name+k'."""
    import bisect
    lin = v if v >= DSEG_BASE else v + DSEG_BASE
    i = bisect.bisect_right(_LKS, lin) - 1
    if i < 0: return None
    k = _LKS[i]; d = lin - k
    if d > 0x800: return None        # too far past the label: not this global
    return LIN2NAME[k] if d == 0 else '%s+%d' % (LIN2NAME[k], d)

OFFMAP = []                  # sorted [(offset,size)] for bare-address size hints
def build_offmap(sym):
    global OFFMAP
    OFFMAP = sorted((off, sz) for off, sz in sym.values() if sz)

def offmap_size(addr):
    import bisect
    keys = [o for o, _ in OFFMAP]
    i = bisect.bisect_right(keys, addr) - 1
    return OFFMAP[i][1] if i >= 0 else ''

REGS = set('ax bx cx dx si di bp sp al ah bl bh cl ch dl dh es ds cs ss '
           'eax ebx ecx edx esi edi ebp esp byte word dword qword tbyte'.split())
# register-name lookup that must run before identifier->X substitution
REGW = {}
for r in 'al ah bl bh cl ch dl dh'.split(): REGW[r] = 'byte'
for r in 'ax bx cx dx si di bp sp'.split(): REGW[r] = 'word'
for r in 'eax ebx ecx edx esi edi ebp esp'.split(): REGW[r] = 'dword'

def subst(ops, sym, varmap):
    """replace names -> offset/bp-ref; return (newops, implied_size, symhit)
    identifiers not in symtab keep their name (callee identity)."""
    implied = ''; hit = False
    def rep(m):
        nonlocal implied, hit
        t = m.group(0)
        if t.lower() in REGS: return t
        if varmap and t in varmap:
            off, sz = varmap[t]; implied = implied or sz; hit = True; return off
        if re.match(r'^(loc_|locret_|sub_|seg0|@\d|@@)', t):
            return 'X'     # autogenerated code labels -> X
        if re.match(r'^@\w+@$', t):
            return 'X'     # IDA __vtable__[class] labels (@button@/@gui_item@) -> X
        m2 = re.match(r'^(?:byte|word|dword|qword|off|unk)_([0-9A-Fa-f]+)$', t)
        if m2:
            implied = implied or {'byte':'byte','word':'word','dword':'dword',
                                  'off':'word','unk':'byte','qword':'qword'}[t.split('_')[0]]
            hit = True
            nm = num2name(int(m2.group(1), 16))   # IDA linear data label -> name
            return nm if nm else str(int(m2.group(1), 16))
        if re.match(r'^a[A-Z]', t) or re.match(r'^asc_\w+$', t) or re.match(r'^s\w*@(\+\d+)?$', t):
            return 'S'     # IDA/BC string label (incl. pooled s@+off) -> S
        # 'gen _name' -> 'orig name': BC++ prepends '_' to C globals, so a gen
        # '_X' is the orig global 'X'. Prefer 'X' if it resolves; else keep '_X'.
        if t.startswith('_') and sym and t[1:] in sym:
            off, sz = sym[t[1:]]; implied = implied or sz; hit = True; return t[1:]
        if sym and t in sym:
            off, sz = sym[t]; implied = implied or sz; hit = True; return t
        return re.sub(r'\$.*', '', t)   # code symbol: strip mangling, keep name
    ops = re.sub(r'(?<![\w@$.])[A-Za-z_@$][\w@$]*', rep, ops)
    ops = re.sub(r's@\+\d+', 'S', ops)
    ops = re.sub(r'S\+\d+', 'S', ops)
    return ops, implied, hit

def normline(l, sym=None, varmap=None):
    l = l.strip()
    if not l or l.startswith(';'): return None
    m = re.match(r'^(seg\w+:)?(?=[0-9A-Fa-f]*[0-9])[0-9A-Fa-f]{3,}\s+(.*)$', l)
    if m: l = m.group(2)
    if not l or l.startswith(';'): return None
    if re.match(r'^[A-Za-z_@$][\w@$]*\s+(equ|=|db|dw|dd|proc|endp|label|assume)\b', l):
        return None
    m = re.match(r'^[A-Za-z_@$][\w@$]*:\s*(.*)$', l)
    if m:
        l = m.group(1).strip()
        if not l or l.startswith(';'): return None
    w = l.split(None, 1)[0]
    if w not in MNEM: return None
    w = ALIAS.get(w, w)
    sp = l.split(None, 1)
    ops = sp[1] if len(sp) > 1 else ''
    ops = ops.split(';')[0]
    ops = re.sub(r'\$[+-]?\d+', 'X', ops)         # jmp $+2 -> jmp X
    ops = re.sub(r'\b(short|near|far|offset|ptr|large)\b', '', ops)
    for a in sorted(RTL_ALIAS, key=len, reverse=True):
        ops = ops.replace(a, RTL_ALIAS[a])
    ops = re.sub(r'\b(byte|word|dword|qword|tbyte)\b', r'\1:', ops)
    ops = re.sub(r'\bDGROUP:?', '', ops)
    ops = re.sub(r'\s+', '', ops)
    out = []
    for op in ops.split(','):
        explicit = re.match(r'^(byte|word|dword|qword|tbyte):', op)
        op2, implied, hit = subst(op, sym, varmap)
        if explicit: implied = ''
        # hex->dec (must start with a digit so 'ah'/'bh' aren't eaten)
        op2 = re.sub(r'(?<![\w:.])(?:0[xX]([0-9a-fA-F]+)|([0-9][0-9a-fA-F]*)[hH])\b',
                     lambda m: str(int(m.group(1) or m.group(2),16)), op2)
        op2 = op2.replace('+-','-').replace('++','+')
        # 'add/sub r,(-)K': x-K == x+(-K) — canonicalize 'add r,-K'->'sub r,K'
        # (handled on the joined insn below); bare '-N' -> unsigned 16-bit
        if re.fullmatch(r'-\d+', op2):
            op2 = str(int(op2) & 0xFFFF)
        # 'push large [dword X]' -> 'push dword:X'
        op2 = re.sub(r'\[(dword|qword):([^\]]+)\]', r'\1:\2', op2)
        # 'push seg <segname|func>' -> 'push seg' (segment-of-module operand;
        # whitespace already stripped so operand abuts 'seg')
        op2 = re.sub(r'^seg[^:]*$', 'seg', op2)
        # switch-jump tables: 'cs:[bx+NUM]' -> 'cs:[bx+X]', 'mov bx,BIG' -> 'mov bx,X'
        # (switch-table `cs:[reg+K]` handled on the joined insn below)
        # fold "NUM[reg+NUM]" -> "[reg+NUM]"
        op2 = re.sub(r'(\d+)\[(bp|bx|si|di)([+-]\d+)?\]',
                     lambda m: '[%s%+d]' % (m.group(2),
                        int(m.group(1)) + int(m.group(3) or 0)), op2)
        # fold "[reg+NUM+NUM...]" -> "[reg+SUM]"
        def _fold(m):
            tot = sum(int(x) for x in re.findall(r'[+-]\d+', m.group(2)))
            return '[%s%+d]' % (m.group(1), tot) if tot else '[%s]' % m.group(1)
        op2 = re.sub(r'\[(bp|bx|si|di)((?:[+-]\d+)+)\]', _fold, op2)
        # resolve data-segment addresses inside [si/di+N] / [N] to names
        # (skip es:/bp: refs — those are member/stack accesses, not data labels)
        if '[' in op2 and 'bp' not in op2 and 'es:' not in op2:
            def _nm(m):
                r = num2name(int(m.group(0)))
                return r if r else m.group(0)
            op2 = re.sub(r'(?<![\w:$.])\d{3,}', _nm, op2)
        op2 = canon_op(op2)
        # size hint for memory/bare-offset operands: explicit > symbol > offmap
        if not explicit and implied and (hit or '[' in op2) \
                and not re.match(r'^(byte|word|dword|qword|tbyte):', op2):
            op2 = implied[0] + ':' + op2
        elif not explicit and not implied and '[' in op2 \
                and not re.search(r'(bp|bx|si|di|sp)', op2):
            am = re.search(r'(\d+)(?=\])', op2)
            if am:
                sz = offmap_size(int(am.group(1)))
                if sz: op2 = sz[0] + ':' + op2
        out.append(op2)
    # normalize short size prefixes b:/w:/d: -> byte:/word:/dword:
    out = [re.sub(r'^(b|w|d):', lambda m: SHORTSZ[m.group(1)+':'], o) for o in out]
    # les/lds always load a far ptr; an explicit size on the mem operand is noise
    if w in ('les', 'lds'):
        out = [re.sub(r'^(byte|word|dword|qword|tbyte):', '', o) if '[' in o else o
               for o in out]
    # strip explicit size prefix when a register operand implies the same size
    sizes = {REGW[o] for o in out if o in REGW}
    out = [re.sub(r'^(byte|word|dword):', '', o)
             if re.match(r'^(byte|word|dword):', o) and o.split(':',1)[0] in sizes
             else o for o in out]
    s = (w + ' ' + ','.join(out)).rstrip()
    # 'mov bx,<jump/value-table addr>' -> 'mov bx,X' (switch table base)
    if re.match(r'^mov bx,\d+$', s) and int(s.split(',')[1]) >= 0x4000:
        s = 'mov bx,X'
    # switch-jump tables: 'cs:[reg+K]' -> 'cs:[reg+X]'
    s = re.sub(r'(cs|ds|ss):\[(bx|si|di)\+\d+\]', r'\1:[\2+X]', s)
    # 'imul r,r,k' (3-op) == 'imul r,k' (2-op)
    s = re.sub(r'^imul (\w+),\1,(-?\d+)$', r'imul \1,\2', s)
    # 'add r,-K' == 'sub r,K' (and vice versa): fold add of a negative
    m = re.match(r'^(add|sub) (\w+),(\d+)$', s)
    if m and m.group(3).isdigit():
        v = int(m.group(3))
        if v >= 0x8000:
            s = ('sub' if m.group(1) == 'add' else 'add') + \
                ' ' + m.group(2) + ',' + str(0x10000 - v)
    return s

def canon_op(op):
    """canonicalize a memory operand: 'NAME+k[reg]' / '[reg+NAME+k]' / 'NAME[reg]'
    -> '[reg+NAME+k]' so equivalent addressing forms compare equal."""
    pre = ''
    m = re.match(r'^((?:(?:byte|word|dword|qword|tbyte|es|ds|cs|ss):)+)', op)
    if m: pre, op = m.group(1), op[len(m.group(1)):]
    if '[' not in op: return pre + op
    op = re.sub(r'([^\[\],]+)\[', lambda m: '[' + m.group(1) + '+', op)
    m = re.match(r'^\[(.*)\]$', op)
    if not m: return pre + op
    toks = [t for t in re.split(r'(?=[+-])', m.group(1)) if t not in ('', '+')]
    regs, names, num = [], [], 0
    for t in toks:
        s = 1
        if t[0] == '-': s, t = -1, t[1:]
        elif t[0] == '+': t = t[1:]
        if t in ('bp','bx','si','di','sp'): regs.append(('-' if s<0 else '')+t)
        elif re.fullmatch(r'\d+', t): num += s*int(t)
        else: names.append(('-' if s<0 else '')+t)
    parts = regs + names + ([str(num)] if num else [])
    return pre + '[' + '+'.join(parts).replace('+-','-') + ']'

def canon_locals(out):
    """map each distinct [bp-N] local offset to L0,L1,... by first appearance,
    so differing local layouts compare equal (args [bp+N] untouched)."""
    mp = {}
    res = []
    for l in out:
        def rep(m):
            k = m.group(0)
            if k not in mp: mp[k] = 'L%d' % len(mp)
            return mp[k]
        # [bp-N] locals and IDA-mislabeled symbolic locals [bp+name+N] (e.g.
        # [bp+amandich+2], where 'name' is a data sym IDA wrongly used for a
        # negative bp offset) -> L#; pure numeric args [bp+N] stay untouched
        l = re.sub(r'\[bp-\d+\]', rep, l)
        l = re.sub(r'\[bp\+[^\]\d][^\]]*\]', rep, l)
        res.append(l)
    return res

def collapse_seq(out):
    """orig linker-opt 'nop;push cs;call near X' -> 'call X' (same-seg far call);
       'mov r8,x / inc|dec r8 / mov x,r8' -> 'inc|dec x' (reg-inc codegen shape)"""
    res, i = [], 0
    while i < len(out):
        if (i+2 < len(out) and out[i] == 'nop' and out[i+1] == 'push cs'
                and out[i+2].startswith('call ')):
            res.append(out[i+2]); i += 3
        elif (i+1 < len(out) and out[i] == 'push cs'
                and out[i+1].startswith('call ')):
            res.append(out[i+1]); i += 2
        elif (i+2 < len(out)
                and re.match(r'^mov (al|ah|bl|bh|cl|ch|dl|dh|ax|bx|cx|dx|si|di),(.*)$', out[i])
                and re.match(r'^(inc|dec|add|sub) ', out[i+1])
                and re.match(r'^mov ', out[i+2])):
            m1 = re.match(r'^mov (\w+),(.*)$', out[i])
            m2 = re.match(r'^(inc|dec|add|sub) (\w+)(?:,(-?\d+))?$', out[i+1])
            m3 = re.match(r'^mov (.*),(\w+)$', out[i+2])
            if m1 and m2 and m3 and m1.group(1) == m2.group(2) \
                    and m1.group(2) == m3.group(1) and m3.group(2) == m1.group(1):
                op = m2.group(1)
                if op in ('add','sub'):
                    v = int(m2.group(3) or 0)
                    r = m1.group(1)
                    bits = 8 if r in REGW and REGW[r] == 'byte' else 16
                    v &= (1 << bits) - 1
                    if v >= (1 << (bits-1)): v -= (1 << bits)   # sign-extend
                    if op == 'sub': v = -v
                    if v not in (1,-1):
                        res.append(out[i]); i += 1; continue
                    op = 'inc' if v == 1 else 'dec'
                sz = REGW.get(m1.group(1), 'byte') + ':'
                res.append(op + ' ' + sz + m3.group(1)); i += 3
            else:
                res.append(out[i]); i += 1
        else:
            res.append(out[i]); i += 1
    return res

_LST_LINES = {}            # lst path -> cached split lines

def _lines(lst):
    if lst not in _LST_LINES:
        _LST_LINES[lst] = open(lst, errors='replace').read().splitlines()
    return _LST_LINES[lst]

_IDX = {}                # lst path -> {funcname: start line index}

def _findex(lst):
    if lst in _IDX: return _IDX[lst]
    idx = {}
    for i, l in enumerate(_lines(lst)):
        m = re.match(r'^seg\w+:[0-9A-Fa-f]+\s+(\S+)\s+proc\b', l)
        if m: idx.setdefault(m.group(1), i); continue
        m = re.match(r'^seg\w+:[0-9A-Fa-f]+\s+([@\w$]+):', l)
        if m: idx.setdefault(m.group(1), i)
    _IDX[lst] = idx
    return idx

def orig_buf(lst, fnpat):
    lines = _lines(lst)
    idx = _findex(lst)
    start0 = idx.get(fnpat, 0)     # exact-name hit: jump to it; else scan from top
    buf, infn, lblmode = [], False, False
    for l in lines[start0:] if fnpat in idx else lines:
        if not infn:
            if re.search(re.escape(fnpat) + r'\s+proc\b', l):
                infn = True
            elif re.search(re.escape(fnpat) + r':', l):
                infn, lblmode = True, True   # label-style fn (no proc keyword)
        else:
            if 'endp' in l: break
            if lblmode:
                # stop at the next function label (@name or proc); internal loc_/data labels continue
                m = re.match(r'^seg\w+:[0-9A-Fa-f]+\s+([@\w$]+):', l)
                if m and not re.match(r'loc|locret|sub_|unk_|off_|word_|byte_|dword_|asc_|a[A-Z]|flt_|dbl_', m.group(1)):
                    break
                if re.match(r'^seg\w+:[0-9A-Fa-f]+\s+[@\w$]+\s+proc\b', l):
                    break
        if infn: buf.append(l)
    return buf

def get_orig(lst, fnpat):
    sym = build_symtab(lst)
    return norm_orig(orig_buf(lst, fnpat), sym)

def norm_orig(buf, sym):
    """normalize a raw orig function body (varmap, labels, canon)."""
    varmap = {}
    for l in buf:
        m = re.match(r'.*?([A-Za-z_]\w*)\s*=\s*(s?byte|s?word|dword|qword|tbyte|\w+)\s+ptr\s+(-?[0-9A-Fa-f]+h?)\b', l)
        if m:
            name, ty, off = m.groups()
            if name in ('assume',): continue
            neg = off.startswith('-')
            off = off.lstrip('-')
            o = int(off[:-1], 16) if off.endswith('h') else \
                (int(off, 16) if re.search('[A-Fa-f]', off) else int(off))
            varmap[name] = (('-%d' if neg else '+%d') % o, ty)
    # collect normalized lines with their seg03f9 addr + jmp-target addr
    rows = []                          # (norm, addr, jtgt_addr|None)
    lbl2addr = {}
    for l in buf:
        m = re.match(r'^seg\w+:([0-9A-Fa-f]+)\s+([A-Za-z_]\w*):', l)
        if m: lbl2addr[m.group(2)] = int(m.group(1), 16)
    for l in buf:
        a = re.match(r'^seg\w+:([0-9A-Fa-f]+)\s+(.*)$', l)
        addr = int(a.group(1), 16) if a else None
        tgt = None
        if a:
            j = re.search(r'\bjmp\s+(?:\w+\s+ptr\s+)?(?:short\s+|near\s+)?(\$[+-]?\d+|loc\w+)', a.group(2))
            if j:
                t = j.group(1)
                if t.startswith('$'): tgt = addr + int(t[1:])
                elif t in lbl2addr: tgt = lbl2addr[t]
        n = normline(l, sym, varmap)
        if n: rows.append((n, addr, tgt))
    # drop unconditional 'jmp' that targets the very next instruction (-O artifact)
    res = []
    for i, (n, addr, tgt) in enumerate(rows):
        if n.startswith('jmp ') and tgt is not None \
                and i + 1 < len(rows) and rows[i+1][1] == tgt:
            continue
        res.append(n)
    return canon_locals(collapse_seq(res))

def get_gen(asm, label_re, sym):
    raw, infn = [], False
    for l in open(asm, errors='replace'):
        l = l.rstrip('\n')
        if label_re in l and 'proc' in l: infn = True; continue
        if infn and 'endp' in l: break
        if not infn: continue
        raw.append(l)
    # pass 1: label -> index of the next normalized insn; collect (norm, raw jmp tgt)
    lbl2idx, rows = {}, []
    for l in raw:
        m = re.match(r'^([@\w$]+|_?[A-Za-z]\w*):\s*$', l)
        if m: lbl2idx[m.group(1).rstrip(':')] = len(rows)
        n = normline(l, sym)
        if n:
            j = re.match(r'^\s*jmp\s+(?:\w+\s+ptr\s+)?(?:short\s+|near\s+)?([@\w$]+|_?[A-Za-z]\w*)', l)
            rows.append((n, j.group(1) if j else None))
    # pass 2: drop unconditional 'jmp' that targets the next insn (-O artifact)
    res = []
    for i, (n, tgt) in enumerate(rows):
        if n.startswith('jmp ') and tgt is not None \
                and tgt in lbl2idx and lbl2idx[tgt] == i + 1:
            continue
        res.append(n)
    return canon_locals(collapse_seq(res))

if __name__ == '__main__':
    sym = build_symtab('RIPTIDE.lst')
    build_name_at(sym); build_offmap(sym)
    orig = get_orig('RIPTIDE.lst', sys.argv[1])
    gen  = get_gen(sys.argv[2], sys.argv[3], sym)
    d = list(difflib.unified_diff(orig, gen, 'ORIG', 'GEN', lineterm='', n=1))
    for l in d: print(l)
    if not d: print("IDENTICAL")
    print(f"--- orig={len(orig)} gen={len(gen)} insns ---")
