#!/usr/bin/env python3
# difftest.py — differential function tests: original RIPTIDE.EXE vs reconstruction.
#
# Runs one far function in each binary under kvikdos with identical inputs
# (stack args + poked memory), then diffs the result registers and the
# declared memory windows.
#
# Address model:
#   original : RIPTIDE.map segment table maps segNAME -> image byte offset;
#              lst addresses are segNAME:off -> runtime seg = 0x110+(start>>4),
#              off' = off + (start & 0xF).
#   recon    : RIPTIDE.MAP publics are already para:off ->
#              runtime seg = 0x110+para, off unchanged.
#   kvikdos  : loads each EXE at image_para 0x110 (PSP_PARA+0x10).

import hashlib, json, os, re, struct, subprocess, sys, tempfile

KVIKDOS = "/home/xor/kvikdos/kvikdos"
ORIG_EXE = "/home/xor/games/Riptide/RIPTIDE.EXE"
ORIG_MAP = "/home/xor/games/Riptide/RIPTIDE.map"
RECON_EXE = "/home/xor/games/Riptide/decomp/link/RIPTIDE.EXE"
RECON_MAP = "/tmp/rpl_clean/RIPTIDE.MAP"
IMAGE_PARA = 0x110

TEST_SS = "0x8000"      # test stack segment (linear 0x80000)
TEST_SP = 0xFF00
SCRATCH = 0x7000        # scratch segment for this-objects / pointed data


def parse_map(path):
    """Return (segs{name:start_byte}, syms{name:(para,off)}, segaddrs{para:name})."""
    segs, syms = {}, {}
    with open(path, errors="replace") as f:
        section = None
        for line in f:
            m = re.match(r"\s*([0-9A-F]+)H\s+([0-9A-F]+)H\s+([0-9A-F]+)H\s+(\S+)\s+(\S+)", line)
            if m:
                segs[m.group(4).lower()] = int(m.group(1), 16)
                section = "pubs" if False else section
                continue
            m = re.match(r"\s*([0-9A-F]+):([0-9A-F]+)\s+(.+?)\s*$", line)
            if m:
                name = m.group(3).strip()
                syms.setdefault(name, (int(m.group(1), 16), int(m.group(2), 16)))
    return segs, syms


ORIG_SEGS, ORIG_SYMS = parse_map(ORIG_MAP)
RECON_SEGS, RECON_SYMS = parse_map(RECON_MAP)


def orig_addr(segname, off):
    """lst addresses segNNNN:off are relative to the segment's paragraph base
    (MAP Start is in bytes; base = Start & ~0xF)."""
    start = ORIG_SEGS[segname.lower()]
    return IMAGE_PARA + (start >> 4), off


def recon_addr(symname):
    para, off = RECON_SYMS[symname]
    return IMAGE_PARA + para, off


def dgroup_para(segs, segname="seg2608"):
    """DGROUP runtime segment = image_para + (dgroup byte start >> 4)."""
    return IMAGE_PARA + (segs[segname] >> 4)


ORIG_DG = dgroup_para(ORIG_SEGS)
RECON_DG = dgroup_para(RECON_SEGS)

PROVEN_JSON = "/home/xor/games/Riptide/tools/z3cmp/proven_equal.json"


def load_proven_names(path=PROVEN_JSON):
    """Function names fully Z3-proven equivalent (see tools/mkproven.py).

    The registry records machine-code SHA-256 per part; it is regenerated by
    re-running the compare pipeline, so proofs are 'valid until changed'.
    """
    try:
        reg = json.load(open(path))
    except OSError:
        return set()
    return set((reg.get("proven") or {}).keys())


def load_proven_linears(path=PROVEN_JSON):
    """Oracle function-entry image-linear addresses of Z3-proven functions."""
    try:
        reg = json.load(open(path))
    except OSError:
        return set()
    return set(reg.get("proven_linear") or [])


def load_proven_exe(path=PROVEN_JSON):
    """proven_exe map: oracle-SSA-linear key -> {orig, recon, candidate_entry}."""
    try:
        reg = json.load(open(path))
    except OSError:
        return {}
    return reg.get("proven_exe") or {}


_EXE_CACHE = {}
_BOUNDS_CACHE = {}


def _exe_image(exe):
    if exe not in _EXE_CACHE:
        data = open(exe, "rb").read()
        _EXE_CACHE[exe] = data[int.from_bytes(data[8:10], "little") * 16 :]
    return _EXE_CACHE[exe]


def _exe_bounds(funcs_json):
    if funcs_json not in _BOUNDS_CACHE:
        bounds = []
        try:
            for f in json.load(open(funcs_json)).get("functions", []):
                lin = (f.get("entry") or {}).get("linear")
                if lin is not None:
                    bounds.append(int(lin, 0))
        except OSError:
            pass
        _BOUNDS_CACHE[funcs_json] = sorted(set(bounds))
    return _BOUNDS_CACHE[funcs_json]


def _function_exe_sha(exe, funcs_json, ssa_linear):
    """mkproven-compatible hash: [entry, next catalog entry) of the image."""
    image_byte = int(ssa_linear, 0) - 0x1000
    image = _exe_image(exe)
    if image_byte < 0 or image_byte >= len(image):
        return None
    end = len(image)
    for bound in _exe_bounds(funcs_json):
        if bound > image_byte:
            end = min(end, bound)
            break
    return hashlib.sha256(image[image_byte:end]).hexdigest()


ORIG_FUNCS_JSON = "/home/xor/games/Riptide/tools/z3cmp/orig_funcs.json"
RECON_FUNCS_JSON = "/home/xor/games/Riptide/tools/z3cmp/recon_funcs.json"


def _proven_still_valid(linear, proven_exe):
    """Check recorded orig/recon machine-code hashes against current EXEs."""
    rec = proven_exe.get("0x%05x" % linear)
    if not isinstance(rec, dict):
        return True  # no hash record -> registry alone decides
    if rec.get("orig") is not None and _function_exe_sha(
        ORIG_EXE, ORIG_FUNCS_JSON, linear
    ) != rec["orig"]:
        return False
    cand = rec.get("candidate_entry")
    if rec.get("recon") is not None and cand is not None and _function_exe_sha(
        RECON_EXE, RECON_FUNCS_JSON, cand
    ) != rec["recon"]:
        return False
    return True


def _orig_names_for_test(t):
    """ORIG map public names at the test's orig_loc runtime address."""
    loc = t.orig_loc
    segname, off = loc if isinstance(loc, tuple) else ("seg0000", int(loc))
    try:
        para, off = orig_addr(segname, off)
    except KeyError:
        return set()
    return {n for n, (p, o) in ORIG_SYMS.items() if IMAGE_PARA + p == para and o == off}


def _orig_linear_for_test(t):
    """Test's orig_loc as an SSA `linear` address.

    DOSUnit SSA linear = image byte offset + 0x1000 (its 0x100-para load bias);
    image byte = (segment Start & ~0xF) + off.
    """
    loc = t.orig_loc
    segname, off = loc if isinstance(loc, tuple) else ("seg0000", int(loc))
    try:
        start = ORIG_SEGS[segname.lower()]
    except KeyError:
        return None
    return (start & ~0xF) + off + 0x1000


SENTINEL = {"ax": 0x1111, "cx": 0x2222, "dx": 0x3333, "bx": 0x4444,
            "si": 0x5555, "di": 0x6666, "bp": 0x7777}

# ax = near return value; memory windows & flags = observable effects -> DIFF.
# dx:ax long/far-ptr returns make dx ambiguous -> WARN tier unless test opts in.
CMP_RESULT = ("ax", "flags")
CMP_SCRATCH = ("bx", "cx", "dx", "si", "di", "bp", "sp")


def run_kvikdos(exe, fn_seg, fn_off, ds, args, pokes, dump_path, extra_poke_files=()):
    cmd = [KVIKDOS, "--diag=off",
           f"--call-far=0x{fn_seg:x}:0x{fn_off:x}",
           f"--call-ds=0x{ds:x}",
           f"--call-ss=0x{int(TEST_SS,16):x}:0x{TEST_SP:x}",
           f"--hlt-dump={dump_path}"]
    for reg, val in SENTINEL.items():
        cmd.append(f"--call-set={reg}:0x{val:x}")
    for a in args:
        cmd.append(f"--call-arg=0x{a & 0xffff:x}")
    for (seg, off, val) in pokes:
        cmd.append(f"--poke-word=0x{seg:x}:0x{off:x}:0x{val & 0xffff:x}")
    for pf in extra_poke_files:
        cmd.append(pf)
    cmd.append(exe)
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    res = {}
    m = re.search(r"kvikdos-call-result (.*)", p.stdout)
    if m:
        for kv in m.group(1).split():
            k, v = kv.split("=")
            res[k] = int(v, 16)
    return res, p.stdout + p.stderr, p.returncode


def fmt_regs(res):
    keys = ["ax", "bx", "cx", "dx", "si", "di", "bp", "sp", "ds", "es", "ss", "flags"]
    return " ".join(f"{k}={res.get(k, 0):04x}" for k in keys)


class Test:
    def __init__(self, name, orig_loc, recon_loc, args=(), pokes=(), windows=(),
                 pokes_recon_off=None):
        """orig_loc: (segname, off) or int off into seg0000-name.
        recon_loc: public symbol name from recon MAP.
        pokes: list of (seg_or_'dg', off, val); 'dg' resolved per-build.
        windows: list of (seg_or_'dg', off, size) memory regions to diff;
                 (seg,off) absolute or ('dg',off) DGROUP-relative.
        """
        self.name = name
        self.orig_loc = orig_loc
        self.recon_loc = recon_loc
        self.args = list(args)
        self.pokes = list(pokes)
        self.windows = list(windows)


def resolve(seg_or_dg, dg, syms):
    """Poke/window segment spec -> (seg, base_off).
    'dg' -> DGROUP para; 'sym:NAME' -> seg of public symbol NAME (off = sym's)."""
    if seg_or_dg == "dg":
        return dg, 0
    if isinstance(seg_or_dg, str) and seg_or_dg.startswith("sym:"):
        para, off = syms[seg_or_dg[4:]]
        return IMAGE_PARA + para, off
    return seg_or_dg, 0


def run_test(t, verbose=False):
    results = {}
    dgs = {"orig": ORIG_DG, "recon": RECON_DG}
    locs = {"orig": orig_addr(*t.orig_loc),
            "recon": recon_addr(t.recon_loc)}
    symss = {"orig": ORIG_SYMS, "recon": RECON_SYMS}
    for tag, exe in (("orig", ORIG_EXE), ("recon", RECON_EXE)):
        dg = dgs[tag]
        pokes = []
        for (s, o, v) in t.pokes:
            rs, ro = resolve(s, dg, symss[tag])
            pokes.append((rs, ro + o, v))
        dumpdir = "/dev/shm" if os.path.isdir("/dev/shm") else "/tmp"
        dump = f"{dumpdir}/dt_{t.name}_{tag}.bin"
        res, out, rc = run_kvikdos(exe, *locs[tag], dg, t.args, pokes, dump)
        mem = open(dump, "rb").read() if os.path.exists(dump) else b""
        results[tag] = (res, mem, out, rc)
    # diff regs
    ok = True
    diffs = []
    ro, rr = results["orig"][0], results["recon"][0]
    if not ro:
        diffs.append("orig produced no kvikdos-call-result (crash/timeout?)")
        ok = False
    if not rr:
        diffs.append("recon produced no kvikdos-call-result (crash/timeout?)")
        ok = False
    warns = []
    if ro and rr:
        for k in CMP_RESULT:
            if k in ro and k in rr and ro[k] != rr[k]:
                diffs.append(f"reg {k}: orig={ro[k]:04x} recon={rr[k]:04x}")
                ok = False
        for k in CMP_SCRATCH:
            if k in ro and k in rr and ro[k] != rr[k]:
                warns.append(f"reg {k}: orig={ro[k]:04x} recon={rr[k]:04x}")
    # diff windows
    for (s, o, n) in t.windows:
        wso, woo = resolve(s, dgs["orig"], ORIG_SYMS)
        wsr, wro = resolve(s, dgs["recon"], RECON_SYMS)
        mo = results["orig"][1]
        mr = results["recon"][1]
        lo = wso * 16 + woo + o
        lr = wsr * 16 + wro + o
        wo = mo[lo:lo + n]
        wrb = mr[lr:lr + n]
        if wo != wrb:
            ok = False
            diffs.append(f"mem window dg+{o:x} len={n} differs")
            for i in range(0, min(len(wo), len(wrb)), 2):
                a = wo[i:i + 2]
                b = wrb[i:i + 2]
                if a != b:
                    diffs.append(f"  +{i:03x}: orig={a.hex()} recon={b.hex()}")
                    if sum(1 for d in diffs if d.startswith("  +")) > 8:
                        diffs.append("  ...")
                        break
    status = "PASS" if ok and not warns else ("DIFF" if not ok else "WARN")
    print(f"{status} {t.name}")
    for d in diffs[:16]:
        print(f"     {d}")
    for w in warns[:8]:
        print(f"     ~{w}")
    if verbose:
        for tag in ("orig", "recon"):
            print(f"     {tag}: {fmt_regs(results[tag][0])} rc={results[tag][3]}")
            tail = results[tag][2].strip().splitlines()
            for ln in tail[-3:]:
                print(f"       | {ln}")
    return ok


# ---------------------------------------------------------------------------
# Test specs
# ---------------------------------------------------------------------------

SCR = SCRATCH  # shorthand
TESTS = [
    # --- harness sanity: pure leaf, identical codegen expected --------------
    Test("abs_neg",  ("seg03f9", 0x72A4), "abs(int)", args=[-5]),
    Test("abs_pos",  ("seg03f9", 0x72A4), "abs(int)", args=[37]),
    Test("abs_zero", ("seg03f9", 0x72A4), "abs(int)", args=[0]),
    Test("abs_min",  ("seg03f9", 0x72A4), "abs(int)", args=[-32768]),
    # --- random: exercises nested far call (_rand) + seeded DGROUP state ----
    Test("random_100", ("seg03f9", 0x7280), "random(int)", args=[100]),
    Test("random_1",   ("seg03f9", 0x7280), "random(int)", args=[1]),
    # --- clear_flags: far 'this' write, verifies memory window --------------
    Test("clear_flags", ("seg110e", 0x0480), "game_manager::clear_flags()",
         args=[0x0000, SCR],
         pokes=[(SCR, 8 + 2 * i, 0xAAAA) for i in range(10)],
         windows=[(SCR, 0, 40)]),
    # --- touching: two m_actor far*, all-zero flag words -> geometry path ---
    Test("touching_same", ("seg1224", 0x0CBD),
         "touching(m_actor far*,m_actor far*)",
         args=[0x0000, SCR, 0x0100, SCR],
         pokes=[(SCR, 0x52, 0), (SCR, 0x152, 0)]),
    # bit0 of +0x52 set on arg A -> early-return-0 path
    Test("touching_flag0", ("seg1224", 0x0CBD),
         "touching(m_actor far*,m_actor far*)",
         args=[0x0000, SCR, 0x0100, SCR],
         pokes=[(SCR, 0x52, 1), (SCR, 0x152, 0)]),
]

# ---------------------------------------------------------------------------
# Collision suite: tile_collision / check_new_pos / touching pixel path.
#
# Scratch layout (seg 0x7000):
#   0x000 actor A (m_actor)      0x100 barrier actor B
#   0x300 out-word area          0x400 map object (map+0x8E=w, map+0x39E=tiles ptr)
#   0x500/0x520 loop_res A/B     0x600/0x620 cel (gm_frame) A/B
#   0x700/0x740 bitmap A/B       0x800 tile array (dword entries, <0x100 blocked)
# Map width 8 -> tbl_mul_tw[i] = 8*i.  Actor A box = tiles 10,11/18,19 (2x2).
# ---------------------------------------------------------------------------

_DG_MAP   = 0x3822   # _the_map (far*)
_DG_MUL   = 0x3826   # _tbl_mul_tw
_DG_BCNT  = 0x351C   # _barrier_count (byte)
_DG_BLIST = 0x352A   # _barrier_list (far*[])

MAP_POKES = [
    ("dg", _DG_MAP + 0, 0x0400), ("dg", _DG_MAP + 2, SCR),      # _the_map
    ("dg", _DG_MUL + 0, 0), ("dg", _DG_MUL + 2, 8),             # tbl_mul_tw
    ("dg", _DG_MUL + 4, 16), ("dg", _DG_MUL + 6, 24),
    (SCR, 0x400 + 0x39E, 0x0800), (SCR, 0x400 + 0x3A0, SCR),    # map->tiles
    (SCR, 0x400 + 0x8E, 8),                                     # map width
]
TILE_FREE = [(SCR, 0x800 + t * 4, 0x0200) for t in (10, 11, 18, 19)]
ACTOR_A_BASE = [
    (SCR, 0x00, 16), (SCR, 0x02, 8),          # x,y
    (SCR, 0x10, 8), (SCR, 0x12, 8),           # w,h px
    (SCR, 0x14, 0), (SCR, 0x16, 0),           # x_step,y_step
    (SCR, 0x18, 10), (SCR, 0x1A, 2), (SCR, 0x1C, 2),  # tile idx, w_t, h_t
    (SCR, 0x52, 0),                           # signal flags
]

TESTS += [
    # --- m_actor::tile_collision(this,a,b,c): box-edge bitmask --------------
    Test("tilecol_open", ("seg1224", 0x0AB8),
         "m_actor::tile_collision(int,int,int)",
         args=[0x0000, SCR, 0, 0, 0],
         pokes=MAP_POKES + TILE_FREE + ACTOR_A_BASE),
    Test("tilecol_top_right", ("seg1224", 0x0AB8),
         "m_actor::tile_collision(int,int,int)",
         args=[0x0000, SCR, 0, 0, 0],
         pokes=MAP_POKES + TILE_FREE + [(SCR, 0x800 + 11 * 4, 0x0001)]
              + ACTOR_A_BASE),
    Test("tilecol_bot_left", ("seg1224", 0x0AB8),
         "m_actor::tile_collision(int,int,int)",
         args=[0x0000, SCR, 0, 0, 0],
         pokes=MAP_POKES + TILE_FREE + [(SCR, 0x800 + 18 * 4, 0x0001)]
              + ACTOR_A_BASE),
    # explicit dims a=4,b=1,c=0 -> w=4,h=1; row stride tbl[0]=0 rescan
    Test("tilecol_dims", ("seg1224", 0x0AB8),
         "m_actor::tile_collision(int,int,int)",
         args=[0x0000, SCR, 4, 1, 0],
         pokes=MAP_POKES + TILE_FREE
              + [(SCR, 0x800 + 12 * 4, 0x0200), (SCR, 0x800 + 13 * 4, 0x0200)]
              + ACTOR_A_BASE),
    # --- check_new_pos(actor,newx,newy,o1,o2,f1,f2,f3) ----------------------
    Test("checkpos_open", ("seg0b2c", 0x0225),
         "check_new_pos(m_actor far*,int,int,int far*,int far*,int,int,int)",
         args=[0x0000, SCR, 16, 8, 0x0300, SCR, 0x0302, SCR, 0, 0, 0],
         pokes=MAP_POKES + TILE_FREE + ACTOR_A_BASE
              + [("dg", _DG_BCNT, 0)],
         windows=[(SCR, 0x00, 0x1E), (SCR, 0x300, 4)]),
    Test("checkpos_wall", ("seg0b2c", 0x0225),
         "check_new_pos(m_actor far*,int,int,int far*,int far*,int,int,int)",
         args=[0x0000, SCR, 16, 8, 0x0300, SCR, 0x0302, SCR, 0, 0, 0],
         pokes=MAP_POKES + TILE_FREE + [(SCR, 0x800 + 11 * 4, 0x0001)]
              + ACTOR_A_BASE + [("dg", _DG_BCNT, 0)],
         windows=[(SCR, 0x00, 0x1E), (SCR, 0x300, 4)]),
    # barrier overlaps A by 1x1 px (A x16..24 y8..16; B x23..31 y15..23)
    # -> touching pixel path: bmpA[63]&bmpB[0] nonzero => ax=0x80
    Test("checkpos_barrier", ("seg0b2c", 0x0225),
         "check_new_pos(m_actor far*,int,int,int far*,int far*,int,int,int)",
         args=[0x0000, SCR, 16, 8, 0x0300, SCR, 0x0302, SCR, 0, 0, 0],
         pokes=MAP_POKES + TILE_FREE + ACTOR_A_BASE + [
            ("dg", _DG_BCNT, 1),
            ("dg", _DG_BLIST + 0, 0x0100), ("dg", _DG_BLIST + 2, SCR),
            # actor A pixel chain
            (SCR, 0x3C, 0), (SCR, 0x46, 0x0500), (SCR, 0x48, SCR),
            (SCR, 0x500 + 6, 0x0600), (SCR, 0x500 + 8, SCR),   # loopA->cels[0]
            (SCR, 0x600 + 0, 0x0700), (SCR, 0x600 + 2, SCR),   # celA->bitmap
            # barrier B
            (SCR, 0x100 + 0x00, 23), (SCR, 0x100 + 0x02, 15),
            (SCR, 0x100 + 0x10, 8), (SCR, 0x100 + 0x12, 8),
            (SCR, 0x100 + 0x52, 0), (SCR, 0x100 + 0x3C, 0),
            (SCR, 0x100 + 0x46, 0x0520), (SCR, 0x100 + 0x48, SCR),
            (SCR, 0x520 + 6, 0x0620), (SCR, 0x520 + 8, SCR),
            (SCR, 0x620 + 0, 0x0740), (SCR, 0x620 + 2, SCR),
            # pixels: cover +-8 bytes around expected offsets
            (SCR, 0x700 + 56, 0x0101), (SCR, 0x700 + 58, 0x0101),
            (SCR, 0x700 + 60, 0x0101), (SCR, 0x700 + 62, 0x0101),
            (SCR, 0x740 + 0, 0x0101), (SCR, 0x740 + 2, 0x0101),
            (SCR, 0x740 + 4, 0x0101), (SCR, 0x740 + 6, 0x0101),
         ],
         windows=[(SCR, 0x00, 0x1E), (SCR, 0x300, 4)]),
]

# ---------------------------------------------------------------------------
# Hit / LOS suite: check_for_hit (damage resolution), check_horizontal_ray
# and check_vertical_ray (enemy line-of-sight through the tile map).
# ---------------------------------------------------------------------------

_DG_CURSUB = 0x34B4  # _cur_sub (far*)

TESTS += [
    # check_for_hit(actor, damage): +0x52 bit3 = hit flag, +0x28 = threshold,
    # returns 0 (no hit flag) / 1 (damage>threshold, survives) / 2 (destroyed)
    Test("hitflag_clear", ("seg0b2c", 0x00BF),
         "check_for_hit(m_actor far*,unsigned char)",
         args=[0x0000, SCR, 5],
         pokes=[(SCR, 0x52, 0), (SCR, 0x28, 10)],
         windows=[(SCR, 0x30, 0x24)]),
    Test("hitflag_dmg_le", ("seg0b2c", 0x00BF),
         "check_for_hit(m_actor far*,unsigned char)",
         args=[0x0000, SCR, 5],
         pokes=[(SCR, 0x52, 8), (SCR, 0x28, 10)],
         windows=[(SCR, 0x30, 0x24)]),
    Test("hitflag_dmg_gt", ("seg0b2c", 0x00BF),
         "check_for_hit(m_actor far*,unsigned char)",
         args=[0x0000, SCR, 15],
         pokes=[(SCR, 0x52, 8), (SCR, 0x28, 10)],
         windows=[(SCR, 0x30, 0x24)]),
    Test("hitflag_dmg_eq", ("seg0b2c", 0x00BF),
         "check_for_hit(m_actor far*,unsigned char)",
         args=[0x0000, SCR, 10],
         pokes=[(SCR, 0x52, 8), (SCR, 0x28, 10)],
         windows=[(SCR, 0x30, 0x24)]),
    # check_horizontal_ray(actor, dist): facing+0x34==0 scans right from
    # tile 18+w_t=20; !=0 scans left from 18.  Row = my_map_pos + tbl[h_t/2].
    Test("hray_right_clear", ("seg0b2c", 0x01A9),
         "check_horizontal_ray(m_actor far*,unsigned int)",
         args=[0x0000, SCR, 3],
         pokes=MAP_POKES + ACTOR_A_BASE + [(SCR, 0x34, 0)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (20, 21, 22)]),
    Test("hray_right_blocked", ("seg0b2c", 0x01A9),
         "check_horizontal_ray(m_actor far*,unsigned int)",
         args=[0x0000, SCR, 3],
         pokes=MAP_POKES + ACTOR_A_BASE + [(SCR, 0x34, 0)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (20, 22)]
              + [(SCR, 0x800 + 21 * 4, 0x0001)]),
    Test("hray_left_blocked", ("seg0b2c", 0x01A9),
         "check_horizontal_ray(m_actor far*,unsigned int)",
         args=[0x0000, SCR, 3],
         pokes=MAP_POKES + ACTOR_A_BASE + [(SCR, 0x34, 1)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (17, 18)]
              + [(SCR, 0x800 + 16 * 4, 0x0001)]),
    # check_vertical_ray(actor, dist): actor+0xA < _cur_sub+0xA scans down
    # from bottom row (tbl[h_t-1]); else up from top row.  w_t cols each.
    Test("vray_down_clear", ("seg0b2c", 0x0109),
         "check_vertical_ray(m_actor far*,unsigned int)",
         args=[0x0000, SCR, 2],
         pokes=MAP_POKES + ACTOR_A_BASE
              + [("dg", _DG_CURSUB + 0, 0x0200), ("dg", _DG_CURSUB + 2, SCR),
                 (SCR, 0x0A, 16), (SCR, 0x200 + 0x0A, 30)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (18, 19, 26, 27)]),
    Test("vray_down_blocked", ("seg0b2c", 0x0109),
         "check_vertical_ray(m_actor far*,unsigned int)",
         args=[0x0000, SCR, 2],
         pokes=MAP_POKES + ACTOR_A_BASE
              + [("dg", _DG_CURSUB + 0, 0x0200), ("dg", _DG_CURSUB + 2, SCR),
                 (SCR, 0x0A, 16), (SCR, 0x200 + 0x0A, 30)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (18, 19, 27)]
              + [(SCR, 0x800 + 26 * 4, 0x0001)]),
    Test("vray_up_blocked", ("seg0b2c", 0x0109),
         "check_vertical_ray(m_actor far*,unsigned int)",
         args=[0x0000, SCR, 2],
         pokes=MAP_POKES + ACTOR_A_BASE
              + [("dg", _DG_CURSUB + 0, 0x0200), ("dg", _DG_CURSUB + 2, SCR),
                 (SCR, 0x0A, 30), (SCR, 0x200 + 0x0A, 16)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (10, 11)]
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (3,)]
              + [(SCR, 0x800 + 2 * 4, 0x0001)]),
]

# ---------------------------------------------------------------------------
# Misc suite: hit_cur_sub, check_flying_death, check_in_window (the
# in_window bit gating shootable lists), on_tile/on_pos/facing_actor.
# ---------------------------------------------------------------------------

_TESTS_SUB = [("dg", _DG_CURSUB + 0, 0x0200), ("dg", _DG_CURSUB + 2, SCR)]

TESTS += [
    # hit_cur_sub(dmg, xstep): cur_sub +0x52|=8(hit), +0x28+=dmg, +0x1E=xstep
    Test("hitsub", ("seg0b2c", 0x000D), "hit_cur_sub(int,int)",
         args=[3, -5],
         pokes=_TESTS_SUB + [(SCR, 0x200 + 0x52, 0), (SCR, 0x200 + 0x28, 7),
                             (SCR, 0x200 + 0x1E, 0)],
         windows=[(SCR, 0x200 + 0x1E, 0x36)]),
    # check_flying_death(actor): status+0x3D==2 -> y_step++; if !in_window
    # (+0x52 bit1) -> deleting bit0
    Test("flydeath_inwin", ("seg0b2c", 0x008F),
         "check_flying_death(m_actor far*)",
         args=[0x0000, SCR],
         pokes=[(SCR, 0x3C, 0x200), (SCR, 0x16, 5), (SCR, 0x52, 2)],
         windows=[(SCR, 0x14, 0x40)]),
    Test("flydeath_nowin", ("seg0b2c", 0x008F),
         "check_flying_death(m_actor far*)",
         args=[0x0000, SCR],
         pokes=[(SCR, 0x3C, 0x200), (SCR, 0x16, 5), (SCR, 0x52, 0)],
         windows=[(SCR, 0x14, 0x40)]),
    Test("flydeath_alive", ("seg0b2c", 0x008F),
         "check_flying_death(m_actor far*)",
         args=[0x0000, SCR],
         pokes=[(SCR, 0x3C, 0x100), (SCR, 0x16, 5), (SCR, 0x52, 0)],
         windows=[(SCR, 0x14, 0x40)]),
    # check_in_window: actor box vs map view rect -> +0x52 bit1
    # map+0x0C=vx,+0x18=vw,+0x0E=vy,+0x1A=vh ; actor+0=x,+4=xw,+2=y,+6=yh
    Test("inwin_inside", ("seg1224", 0x0221),
         "m_actor::check_in_window()",
         args=[0x0000, SCR],
         pokes=MAP_POKES[:2]
              + [(SCR, 0x400 + 0x0C, 0), (SCR, 0x400 + 0x18, 320),
                 (SCR, 0x400 + 0x0E, 0), (SCR, 0x400 + 0x1A, 200)]
              + [(SCR, 0x00, 16), (SCR, 0x02, 8), (SCR, 0x04, 24),
                 (SCR, 0x06, 16), (SCR, 0x52, 0)],
         windows=[(SCR, 0x52, 2)]),
    Test("inwin_outside", ("seg1224", 0x0221),
         "m_actor::check_in_window()",
         args=[0x0000, SCR],
         pokes=MAP_POKES[:2]
              + [(SCR, 0x400 + 0x0C, 0), (SCR, 0x400 + 0x18, 320),
                 (SCR, 0x400 + 0x0E, 0), (SCR, 0x400 + 0x1A, 200)]
              + [(SCR, 0x00, 400), (SCR, 0x02, 8), (SCR, 0x04, 408),
                 (SCR, 0x06, 16), (SCR, 0x52, 2)],
         windows=[(SCR, 0x52, 2)]),
    # on_tile(v): row+1 if any box tile equals v, else 0
    Test("ontile_yes", ("seg1224", 0x0BD5), "m_actor::on_tile(int)",
         args=[0x0000, SCR, 0x0777],
         pokes=MAP_POKES + TILE_FREE + ACTOR_A_BASE
              + [(SCR, 0x800 + 10 * 4, 0x0777)]),
    Test("ontile_no", ("seg1224", 0x0BD5), "m_actor::on_tile(int)",
         args=[0x0000, SCR, 0x0777],
         pokes=MAP_POKES + TILE_FREE + ACTOR_A_BASE),
    # on_pos(pos): 1 if tile index inside actor box else 0
    Test("onpos_yes", ("seg1224", 0x0C53), "m_actor::on_pos(unsigned int)",
         args=[0x0000, SCR, 18],
         pokes=MAP_POKES + ACTOR_A_BASE),
    Test("onpos_no", ("seg1224", 0x0C53), "m_actor::on_pos(unsigned int)",
         args=[0x0000, SCR, 12],
         pokes=MAP_POKES + ACTOR_A_BASE),
    # facing_actor(other): +8 edge compare + facing+0x34 -> 1/0
    Test("facing_left", ("seg1224", 0x01DE),
         "m_actor::facing_actor(m_actor far*)",
         args=[0x0000, SCR, 0x0100, SCR],
         pokes=[(SCR, 0x08, 24), (SCR, 0x34, 0),
                (SCR, 0x108, 31)]),
    Test("facing_right", ("seg1224", 0x01DE),
         "m_actor::facing_actor(m_actor far*)",
         args=[0x0000, SCR, 0x0100, SCR],
         pokes=[(SCR, 0x08, 31), (SCR, 0x34, 1),
                (SCR, 0x108, 24)]),
    Test("facing_wrongway", ("seg1224", 0x01DE),
         "m_actor::facing_actor(m_actor far*)",
         args=[0x0000, SCR, 0x0100, SCR],
         pokes=[(SCR, 0x08, 24), (SCR, 0x34, 1),
                (SCR, 0x108, 31)]),
]

# ---------------------------------------------------------------------------
# mv_ego suite: the player movement gate — check_new_pos with sub dims
# (_ego_map_w/_ego_map_h, c=1) vs jason dims (4,2,0).  dx/dy are out-ptrs
# carrying the requested new position; on block they're reset to actor x/y
# and the matching step is zeroed.
# ---------------------------------------------------------------------------

_DG_JASON  = 0x34B0  # _jason (far*)
_DG_EGW    = 0x34F2  # _ego_map_w
_DG_EGH    = 0x34F4  # _ego_map_h

# sub path: tile_collision(a=4,b=2,c=1) -> scans tiles {11,12,13,19,20,21}
_SUB_TILES = [(SCR, 0x800 + t * 4, 0x0200) for t in (11, 12, 13, 19, 20, 21)]
_MVEGO_BASE = [
    ("dg", _DG_JASON + 0, 0x0200), ("dg", _DG_JASON + 2, SCR),  # _jason = B (not A)
    ("dg", _DG_EGW, 4), ("dg", _DG_EGH, 2),
    ("dg", _DG_BCNT, 0),
    (SCR, 0x0300, 20), (SCR, 0x0302, 10),                       # *dx,*dy = new pos
]

TESTS += [
    Test("mvego_open_sub", ("seg0b2c", 0x0372),
         "mv_ego(m_actor far*,int far*,int far*)",
         args=[0x0000, SCR, 0x0300, SCR, 0x0302, SCR],
         pokes=MAP_POKES + ACTOR_A_BASE + _SUB_TILES + _MVEGO_BASE,
         windows=[(SCR, 0x300, 4), (SCR, 0x14, 4)]),
    Test("mvego_wall_sub", ("seg0b2c", 0x0372),
         "mv_ego(m_actor far*,int far*,int far*)",
         args=[0x0000, SCR, 0x0300, SCR, 0x0302, SCR],
         pokes=MAP_POKES + ACTOR_A_BASE
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (11, 13, 19, 20, 21)]
              + [(SCR, 0x800 + 12 * 4, 0x0001)] + _MVEGO_BASE,
         windows=[(SCR, 0x300, 4), (SCR, 0x14, 4)]),
    # jason path: _jason == actor -> tile_collision(4,2,0) scans
    # {10..13,18..21}; block tile 18 -> both clamps
    Test("mvego_wall_jason", ("seg0b2c", 0x0372),
         "mv_ego(m_actor far*,int far*,int far*)",
         args=[0x0000, SCR, 0x0300, SCR, 0x0302, SCR],
         pokes=MAP_POKES + ACTOR_A_BASE
              + [(SCR, 0x800 + t * 4, 0x0200) for t in (10, 11, 12, 13, 19, 20, 21)]
              + [(SCR, 0x800 + 18 * 4, 0x0001)]
              + [("dg", _DG_JASON + 0, 0x0000), ("dg", _DG_JASON + 2, SCR),
                 ("dg", _DG_EGW, 4), ("dg", _DG_EGH, 2), ("dg", _DG_BCNT, 0),
                 (SCR, 0x0300, 20), (SCR, 0x0302, 10)],
         windows=[(SCR, 0x300, 4), (SCR, 0x14, 4)]),
    # door_open bit6 + y_step<=0 -> *dy snap-to-tile-floor clamp attempt
    Test("mvego_snap", ("seg0b2c", 0x0372),
         "mv_ego(m_actor far*,int far*,int far*)",
         args=[0x0000, SCR, 0x0300, SCR, 0x0302, SCR],
         pokes=MAP_POKES + ACTOR_A_BASE + _SUB_TILES
              + [(SCR, 0x52, 0x40), (SCR, 0x16, -1)]
              + [("dg", _DG_JASON + 0, 0x0200), ("dg", _DG_JASON + 2, SCR),
                 ("dg", _DG_EGW, 4), ("dg", _DG_EGH, 2), ("dg", _DG_BCNT, 0),
                 (SCR, 0x0300, 20), (SCR, 0x0302, 20)],
         windows=[(SCR, 0x300, 4)]),
    # *dy<0 -> clamped to 0 before everything
    Test("mvego_dyneg", ("seg0b2c", 0x0372),
         "mv_ego(m_actor far*,int far*,int far*)",
         args=[0x0000, SCR, 0x0300, SCR, 0x0302, SCR],
         pokes=MAP_POKES + ACTOR_A_BASE + _SUB_TILES
              + [("dg", _DG_JASON + 0, 0x0200), ("dg", _DG_JASON + 2, SCR),
                 ("dg", _DG_EGW, 4), ("dg", _DG_EGH, 2), ("dg", _DG_BCNT, 0),
                 (SCR, 0x0300, 20), (SCR, 0x0302, -7)],
         windows=[(SCR, 0x300, 4)]),
]

# ---------------------------------------------------------------------------
# Actor lifecycle: set_xy / move / set_cycle / cycle.
#
# Extra globals: _ego@34A8, _ed_list_size@37FA (byte), _ed_list@366A.
# Loop/cel chain: actor+0x46 -> loop_res; +6 cels[] -> cel (+4=h,+6=w).
# view rect: map+0x0C/+0x0E = vx,vy ; map+0x18/+0x1A = vw,vh.
# ---------------------------------------------------------------------------

_DG_EGO    = 0x34A8
_DG_EDSZ   = 0x37FA
_DG_EDLIST = 0x366A

_VIEW = [(SCR, 0x400 + 0x0C, 0), (SCR, 0x400 + 0x18, 320),
         (SCR, 0x400 + 0x0E, 0), (SCR, 0x400 + 0x1A, 200)]

# loop at 0x500: cels[0..3] -> cel recs at 0x600/0x620/0x640/0x660
# (gm_frame: +4=h, +6=w); dims 8/16/24/32 -> w_t,h_t = 2/3/4/5
_LOOP = [
    (SCR, 0x46, 0x0500), (SCR, 0x48, SCR),
    (SCR, 0x500 + 6, 0x0600), (SCR, 0x500 + 8, SCR),      # cels[0]
    (SCR, 0x500 + 0x0A, 0x0620), (SCR, 0x500 + 0x0C, SCR),  # cels[1]
    (SCR, 0x500 + 0x0E, 0x0640), (SCR, 0x500 + 0x10, SCR),  # cels[2]
    (SCR, 0x500 + 0x12, 0x0660), (SCR, 0x500 + 0x14, SCR),  # cels[3]
    (SCR, 0x600 + 4, 8), (SCR, 0x600 + 6, 8),             # cel0 h,w
    (SCR, 0x620 + 4, 16), (SCR, 0x620 + 6, 16),           # cel1 h,w
    (SCR, 0x640 + 4, 24), (SCR, 0x640 + 6, 24),           # cel2 h,w
    (SCR, 0x660 + 4, 32), (SCR, 0x660 + 6, 32),           # cel3 h,w
]

TESTS += [
    # set_xy(this,x,y): x,y/xw,yh/xw2,yh2/my_map_pos + in_window + ed_list
    Test("setxy", ("seg1224", 0x028B), "m_actor::set_xy(int,int)",
         args=[0x0000, SCR, 100, 50],
         pokes=MAP_POKES[:2] + _VIEW + ACTOR_A_BASE
              + [("dg", _DG_EDSZ, 0), (SCR, 0x10, 8), (SCR, 0x12, 8)],
         windows=[(SCR, 0x00, 0x1A), (SCR, 0x52, 2),
                  ("dg", _DG_EDSZ - 4, 8)]),
    # move(): x+=x_step,y+=y_step; edges/centers/mappos + in_window + ed_list
    Test("move_basic", ("seg1224", 0x0872), "m_actor::move()",
         args=[0x0000, SCR],
         pokes=MAP_POKES[:2] + _VIEW + ACTOR_A_BASE
              + [(SCR, 0x14, 2), (SCR, 0x16, -1),
                 (SCR, 0x3E, 0), (SCR, 0x40, 0),
                 (SCR, 0x42, 0), (SCR, 0x44, 0),
                 ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
                 ("dg", _DG_EDSZ, 0)],
         windows=[(SCR, 0x00, 0x1A), (SCR, 0x52, 2),
                  ("dg", _DG_EDSZ - 4, 8)]),
    Test("move_deleting", ("seg1224", 0x0872), "m_actor::move()",
         args=[0x0000, SCR],
         pokes=MAP_POKES[:2] + _VIEW + ACTOR_A_BASE
              + [(SCR, 0x14, 2), (SCR, 0x16, -1), (SCR, 0x52, 1),
                 (SCR, 0x3E, 0), (SCR, 0x40, 0),
                 (SCR, 0x42, 0), (SCR, 0x44, 0),
                 ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
                 ("dg", _DG_EDSZ, 0)],
         windows=[(SCR, 0x00, 0x1A)]),
    # set_cycle(this,cycler,speed): b in {5,8} -> cur_cel=max_cel-1 + cel dims
    Test("setcycle_plain", ("seg1224", 0x0373),
         "m_actor::set_cycle(unsigned char,unsigned char)",
         args=[0x0000, SCR, 1, 4],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x3B, 4), (SCR, 0x3C, 0)],
         windows=[(SCR, 0x38, 0x20)]),
    Test("setcycle_reverse", ("seg1224", 0x0373),
         "m_actor::set_cycle(unsigned char,unsigned char)",
         args=[0x0000, SCR, 5, 4],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x3B, 4), (SCR, 0x3C, 0)],
         windows=[(SCR, 0x38, 0x20)]),
    # cycle(): cycler switch — count reaches speed -> advance cur_cel
    Test("cycle_wrap", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 1), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 3)],
         windows=[(SCR, 0x10, 0x2E)]),
    Test("cycle_once_del", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 2), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 2), (SCR, 0x52, 0)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_stop", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 3), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 3)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_hold", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 4), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 3)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_bounce0", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 5), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 0)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_bounce_hi", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 6), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 3)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_rebound", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 7), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 0)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_blink", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 8), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 1)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_rand", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 9), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 0)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_wait", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 1), (SCR, 0x39, 1), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 2)],
         windows=[(SCR, 0x38, 0x1C)]),
    Test("cycle_sleep", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 1), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 2), (SCR, 0x52, 0x20)],
         windows=[(SCR, 0x38, 0x1C)]),
    # cel-dim recompute: cur_cel -> cel1 (w16,h16) -> +0x10,+0x12,+0x1A,+0x1C
    Test("cycle_celdim", ("seg1224", 0x0629), "m_actor::cycle()",
         args=[0x0000, SCR],
         pokes=ACTOR_A_BASE + _LOOP
              + [(SCR, 0x38, 1), (SCR, 0x39, 3), (SCR, 0x3A, 3),
                 (SCR, 0x3B, 4), (SCR, 0x3C, 0)],
         windows=[(SCR, 0x10, 0x2E)]),
]

# ---------------------------------------------------------------------------
# Loop lookup: game_manager::get_loop / m_actor::new_loop / turn_ego.
#
# gm @0xA00: +0x38=loop count (byte), +0x3A=loops[] far-ptr array.
# loop_res @0x500: +0=max_cel byte, +2=name far ptr, +6=cels[0].
# name @0x680..: word-packed ASCII. cel0 @0x600 (+4=h,+6=w).
# Globals: _the_game@365A, _jason_on@3524(b), _jason_present@3525(b),
#          _jason_power@34D9(b), _the_cast@34A0.
# ---------------------------------------------------------------------------

_DG_GAME  = 0x365A
_DG_JON   = 0x3524
_DG_JPRES = 0x3525
_DG_JPOW  = 0x34D9
_DG_CAST  = 0x34A0

_GM = [(SCR, 0xA00 + 0x38, 1),                       # loop count = 1
       (SCR, 0xA00 + 0x3A, 0x0500), (SCR, 0xA00 + 0x3C, SCR),
       ("dg", _DG_GAME + 0, 0x0A00), ("dg", _DG_GAME + 2, SCR)]

_LOOPRES = [(SCR, 0x500 + 0, 4),                     # max_cel = 4
            (SCR, 0x500 + 2, 0x0680), (SCR, 0x500 + 4, SCR),  # name
            (SCR, 0x500 + 6, 0x0600), (SCR, 0x500 + 8, SCR),  # cels[0]
            (SCR, 0x600 + 4, 8), (SCR, 0x600 + 6, 8)]         # cel0 h,w

_NAME_TURN = [(SCR, 0x680, 0x7574), (SCR, 0x682, 0x6E72),
              (SCR, 0x684, 0x6C2E), (SCR, 0x686, 0x0000)]     # "turn.l\0"
_NAME_PROBER = [(SCR, 0x680, 0x7270), (SCR, 0x682, 0x626F),
                (SCR, 0x684, 0x7265), (SCR, 0x686, 0x6C2E),
                (SCR, 0x688, 0x0000)]                          # "prober.l\0"

_NL_WIN = [(SCR, 0x0C, 0x44)]                        # +0x0C..+0x4F

TESTS += [
    # get_loop(gm,name): hit -> dx:ax = loop_res; miss -> 0
    Test("getloop_hit", ("seg110e", 0x0FD9),
         "game_manager::get_loop(unsigned char far*)",
         args=[0x0A00, SCR, 0x0680, SCR],
         pokes=_GM + _LOOPRES + _NAME_TURN,
         windows=[]),
    Test("getloop_miss", ("seg110e", 0x0FD9),
         "game_manager::get_loop(unsigned char far*)",
         args=[0x0A00, SCR, 0x0688, SCR],
         pokes=_GM + _LOOPRES + _NAME_TURN + [(SCR, 0x688, 0x6E6F)],  # "no"
         windows=[]),
    # new_loop(actor,name): old dims -> +0x0C/0x0E, my_loop, cel0 dims,
    # edges/centers, count/cel=0, max_cel, +0x52|0x10, +0x4A=name
    Test("newloop", ("seg1224", 0x041C), "m_actor::new_loop(unsigned char far*)",
         args=[0x0000, SCR, 0x0680, SCR],
         pokes=_GM + _LOOPRES + _NAME_TURN + ACTOR_A_BASE
              + [(SCR, 0x10, 8), (SCR, 0x12, 8)],
         windows=_NL_WIN),
    # turn_ego: jason_on=1, jason facing right (+0x34=1) -> "prober.l"
    Test("turn_jason", ("seg03f9", 0x3B43), "turn_ego()",
         pokes=_GM + _LOOPRES + _NAME_PROBER
              + [("dg", _DG_JON, 1), ("dg", _DG_JASON + 0, 0x0300),
                 ("dg", _DG_JASON + 2, SCR),
                 ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
                 ("dg", _DG_CURSUB + 0, 0x0300), ("dg", _DG_CURSUB + 2, SCR)]
              + [(SCR, 0x0300 + 0x34, 1), (SCR, 0x0300 + 0x10, 8),
                 (SCR, 0x0300 + 0x12, 8), (SCR, 0x0300 + 0x00, 100),
                 (SCR, 0x0300 + 0x02, 50)],
         windows=[(SCR, 0x0300 + 0x0C, 0x3E),   # +0x4A holds DS:name ptr (layout-dep)
                  (SCR, 0x0300 + 0x52, 2), (SCR, 0x0300 + 0x34, 2)]),
    # turn_ego: jason_on=0 -> ego: +0x3D=1, +0x22=3, new_loop(ego,"turn.l")
    Test("turn_ego", ("seg03f9", 0x3B43), "turn_ego()",
         pokes=_GM + _LOOPRES + _NAME_TURN
              + [("dg", _DG_JON, 0), ("dg", _DG_JASON + 0, 0x0300),
                 ("dg", _DG_JASON + 2, SCR),
                 ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
                 ("dg", _DG_CURSUB + 0, 0x0200), ("dg", _DG_CURSUB + 2, SCR)]
              + [(SCR, 0x0200 + 0x34, 0), (SCR, 0x0200 + 0x10, 8),
                 (SCR, 0x0200 + 0x12, 8), (SCR, 0x0200 + 0x00, 100),
                 (SCR, 0x0200 + 0x02, 50)],
         windows=[(SCR, 0x0200 + 0x0C, 0x3E),   # +0x4A holds DS:name ptr (layout-dep)
                  (SCR, 0x0200 + 0x52, 2), (SCR, 0x0200 + 0x34, 2),
                  (SCR, 0x0200 + 0x3D, 2), (SCR, 0x0200 + 0x22, 2)]),
]

# ---------------------------------------------------------------------------
# check_user() — input dispatch: the_game+0x27..0x2C = up/down/left/right/
# space/(enter?) key bytes; writes cur_sub +0x14/+0x16 steps, calls turn_ego,
# set_cycle. DG: _control@34CE, _space_bar_been_up@34BC, _ego_x/y_speed@34BD/E,
# _auto_fire@34D6, _auto_fire_count@34D7, _teleport_count@351B, _cheat@34E3,
# _debug_mode@3512, byte_2D3AC@514C, byte_2D3E6@5186, _displayed_page@3526.
# ---------------------------------------------------------------------------

_DG_CTRL   = 0x34CE
_DG_BUP    = 0x34BC
_DG_XSPD   = 0x34BD
_DG_YSPD   = 0x34BE
_DG_AFIRE  = 0x34D6
_DG_AFCNT  = 0x34D7
_DG_TCNT   = 0x351B
_DG_CHEAT  = 0x34E3
_DG_DBG    = 0x3512
_DG_MENU1  = 0x514C
_DG_MENU2  = 0x5186
_DG_DPAGE  = 0x3526

_CU_G = [("dg", _DG_CTRL, 1), ("dg", _DG_BUP, 0), ("dg", _DG_XSPD, 4),
         ("dg", _DG_YSPD, 4), ("dg", _DG_AFIRE, 0), ("dg", _DG_AFCNT, 0),
         ("dg", _DG_TCNT, 0), ("dg", _DG_CHEAT, 0), ("dg", _DG_DBG, 0),
         ("dg", _DG_MENU1, 0), ("dg", _DG_MENU2, 0), ("dg", _DG_DPAGE, 0),
         ("dg", _DG_JON, 0), ("dg", _DG_JPRES, 0),
         ("dg", _DG_GAME + 0, 0x0A00), ("dg", _DG_GAME + 2, SCR),
         ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
         ("dg", _DG_CURSUB + 0, 0x0200), ("dg", _DG_CURSUB + 2, SCR)]

# cur_sub=ego@0x200: dims 8x8 at 100,50; +0x34 face, +0x3D state, +0x14/+0x16 steps
def _cu_actor(xstep=0, ystep=0, face=1, state=0, cycler=0, speed=0):
    return [(SCR, 0x0200 + 0x00, 100), (SCR, 0x0200 + 0x02, 50),
            (SCR, 0x0200 + 0x10, 8), (SCR, 0x0200 + 0x12, 8),
            (SCR, 0x0200 + 0x14, xstep), (SCR, 0x0200 + 0x16, ystep),
            (SCR, 0x0200 + 0x34, face), (SCR, 0x0200 + 0x3D, state),
            (SCR, 0x0200 + 0x38, cycler), (SCR, 0x0200 + 0x3A, speed),
            (SCR, 0x0200 + 0x52, 0)]

_CU_WIN = [(SCR, 0x0200 + 0x14, 4), (SCR, 0x0200 + 0x38, 6),
           ("dg", _DG_BUP, 2), ("dg", _DG_AFCNT, 2)]

def _cu(name, keys, actor=(), extra=(), win=None):
    """keys: list of (gm+off, byte) single-byte sets expressed as word pokes."""
    gmp = [(SCR, 0x0A00 + off, val) for (off, val) in keys]
    return Test(name, ("seg03f9", 0x3BA6), "check_user()",
                pokes=_CU_G + gmp + list(actor) + list(extra),
                windows=list(win) if win else _CU_WIN)

TESTS += [
    _cu("cu_right",   [(0x2A, 1)], _cu_actor(face=0)),
    _cu("cu_left",    [(0x29, 1)], _cu_actor(face=1)),
    # direction change -> turn_ego (ego path -> new_loop "turn.l")
    _cu("cu_right_turn", [(0x2A, 1)], _cu_actor(face=1),
        _GM + _LOOPRES + _NAME_TURN,
        [(SCR, 0x0200 + 0x0C, 0x3E), (SCR, 0x0200 + 0x14, 4),
         (SCR, 0x0200 + 0x22, 2), (SCR, 0x0200 + 0x34, 2),
         (SCR, 0x0200 + 0x38, 6), (SCR, 0x0200 + 0x3D, 2),
         (SCR, 0x0200 + 0x52, 2)]),
    # x-step decay when no x key
    _cu("cu_xdecay_p", [], _cu_actor(xstep=3)),
    _cu("cu_xdecay_n", [], _cu_actor(xstep=-3)),
    # y accel toward +ego_y_speed / -ego_y_speed
    _cu("cu_down",      [(0x28, 1)], _cu_actor(ystep=0)),
    _cu("cu_down_cap",  [(0x28, 1)], _cu_actor(ystep=4)),
    _cu("cu_down_over", [(0x28, 1)], _cu_actor(ystep=5)),
    _cu("cu_up",        [(0x27, 1)], _cu_actor(ystep=0)),
    _cu("cu_up_over",   [(0x27, 1)], _cu_actor(ystep=-5)),
    # y decay when no y key (only if |step|>1)
    _cu("cu_ydecay",    [], _cu_actor(ystep=3)),
    _cu("cu_ystill",    [], _cu_actor(ystep=1)),
    # idle: not moved + speed!=0x0C -> set_cycle(0x0C,1)
    _cu("cu_idle",      [], _cu_actor(speed=4)),
    # control==0 -> early out
    _cu("cu_inactive",  [(0x2A, 1)], _cu_actor(face=1),
        [("dg", _DG_CTRL, 0)]),
    # space held (+0x2B=1) -> been_up update; space released path (been_up=0)
    _cu("cu_space_dn",  [(0x2B, 1)], _cu_actor(face=1)),
    _cu("cu_space_up",  [], _cu_actor(face=1)),
]

# ---------------------------------------------------------------------------
# toggle_sub_control(): swaps _cur_sub between _ego and _jason.
# scroll_to() no-ops when map view center == actor center:
#   var_4 = (map+8 + map+4/2) & ~7, var_6 = (map+A + map+6/2) & ~7
#   phase2 requires var_4 == actor+8 & ~3 && var_6 == actor+A exactly.
# play_sound_file no-ops when gm+0x1C == 0.
# Globals: _non_displayed_page@3527, _display@4788 (unused when aligned).
# ---------------------------------------------------------------------------

_TGL_MAP = [(SCR, 0x400 + 4, 0x280), (SCR, 0x400 + 8, 0),
            (SCR, 0x400 + 6, 0x190), (SCR, 0x400 + 0x0A, 0)]

def _tgl_actor(base):
    return [(SCR, base + 0x08, 320), (SCR, base + 0x0A, 200),
            (SCR, base + 0x14, 3), (SCR, base + 0x16, -2)]

_TGL_G = [("dg", _DG_JPRES, 1), ("dg", _DG_GAME + 0, 0x0A00),
          ("dg", _DG_GAME + 2, SCR),
          ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
          ("dg", _DG_JASON + 0, 0x0300), ("dg", _DG_JASON + 2, SCR)] \
       + MAP_POKES[:2] + _TGL_MAP + _tgl_actor(0x200) + _tgl_actor(0x300)

_TGL_WIN = [(SCR, 0x0200 + 0x14, 4), (SCR, 0x0300 + 0x14, 4),
            ("dg", _DG_JON, 2), ("dg", _DG_CURSUB, 4)]

TESTS += [
    # jason_on=0 -> control to jason: cur_sub=jason, jason_on=1
    Test("tgl_to_jason", ("seg03f9", 0x37A6), "toggle_sub_control()",
         pokes=_TGL_G + [("dg", _DG_JON, 0),
                         ("dg", _DG_CURSUB + 0, 0x0200),
                         ("dg", _DG_CURSUB + 2, SCR)],
         windows=_TGL_WIN),
    # jason_on=1 -> control to sub: ego+0x16=0, cur_sub=ego, jason_on=0
    Test("tgl_to_sub", ("seg03f9", 0x37A6), "toggle_sub_control()",
         pokes=_TGL_G + [("dg", _DG_JON, 1),
                         ("dg", _DG_CURSUB + 0, 0x0300),
                         ("dg", _DG_CURSUB + 2, SCR)],
         windows=_TGL_WIN),
    # jason_present=0 -> early out
    Test("tgl_none", ("seg03f9", 0x37A6), "toggle_sub_control()",
         pokes=_TGL_G + [("dg", _DG_JPRES, 0), ("dg", _DG_JON, 1),
                         ("dg", _DG_CURSUB + 0, 0x0300),
                         ("dg", _DG_CURSUB + 2, SCR)],
         windows=_TGL_WIN),
]

# ---------------------------------------------------------------------------
# game_cast::add / m_actor ctor — allocation path probe.
# cast obj: +0 = count byte (0xC8 full), +2 = far-ptr slot array.
# game_cast::add(cast,name,p2,p3) -> ctor -> new(0x54) -> new_loop.
# ---------------------------------------------------------------------------
TESTS += [
    # cast full -> early return 0
    Test("castadd_full", ("seg1224", 0x0F2F),
         "game_cast::add(unsigned char far*,void far*,void far*)",
         args=[0x0B00, SCR, 0x0680, SCR, 0, 0, 0, 0],
         pokes=_GM + _LOOPRES + _NAME_TURN
              + [(SCR, 0x0B00, 0xC8)],
         windows=[(SCR, 0x0B00, 8)]),
    # ctor with caller-provided ptr (arg_0!=0 -> no new): deterministic
    # m_actor(this, name, moveit->+0x42, doit->+0x3E)
    Test("ctor_init", ("seg1224", 0x0006), "m_actor::m_actor(unsigned char far*,void far*,void far*)",
         args=[0x0200, SCR, 0x0680, SCR, 0x1111, 0x2222, 0x3333, 0x4444],
         pokes=_GM + _LOOPRES + _NAME_TURN + ACTOR_A_BASE
              + [(SCR, 0x0200 + 0x3B, 2)],   # stale max_cel -> cycler=1
         windows=[(SCR, 0x0200, 0x54)]),
    # live alloc path: seed far-heap freelist -> new() should return
    # a deterministic block in scratch space.
    # freelist vars live in seg0000: ___first/___rover/___last -> SCR;
    # free block header at SCR:0: +0=paras, +2=prev?, +6=next(circular), +8=?
    Test("castadd_live", ("seg1224", 0x0F2F),
         "game_cast::add(unsigned char far*,void far*,void far*)",
         args=[0x0B00, SCR, 0x0680, SCR, 0, 0, 0x1111, 0x2222],
         pokes=_GM + _LOOPRES + _NAME_TURN
              + [(SCR, 0x0B00, 0),
                 ("sym:___first", 0, SCR), ("sym:___rover", 0, SCR),
                 ("sym:___last", 0, SCR),
                 (SCR, 0x00, 0x40), (SCR, 0x02, 0), (SCR, 0x06, SCR),
                 (SCR, 0x08, 0)],
         windows=[(SCR, 0x0B00, 10), (SCR, 0x00, 16)]),
]

# ---------------------------------------------------------------------------
# add_missile(actor,type,dir) / ego_fire — projectile creation.
#
# msl_def _all_projectiles[i] at DG+0xEC+i*0x16:
#   +0 snd name far, +4 spr_l far, +8 spr_r far, +0C energy->+0x26,
#   +0D max_speed->+0x24, +0E explosion->+0x22, +10 link->+0x4E,
#   +14 bubbles -> +0x52 bit7.
# get_sound: count gm+0x39, ptrs gm+0x292+i*4; snd rec: +0=name,+4=pri,+6=voc.
# game_cast::add -> new(0x54) -> first alloc lands at 703A:0004.
# Globals: _cur_sound@365E, _the_cast@34A0, _shot_count@34CF,
#          _top_shot_count@34D1, _heavy_timer@34F8.
# ---------------------------------------------------------------------------

_DG_CSND   = 0x365E
_DG_SHCNT  = 0x34CF
_DG_SHSZ   = 0x34D0
_DG_TOPCNT = 0x34D1
_DG_HVY    = 0x34F8
_DG_JFIRE  = 0x34DC
_DG_TFIRE  = 0x34D5
_MSL_BASE  = 0x00EC
ACT_SEG, ACT_OFF = 0x703A, 0x0004          # first far-heap alloc (seeded)

_HEAP = [("sym:___first", 0, SCR), ("sym:___rover", 0, SCR),
         ("sym:___last", 0, SCR),
         (SCR, 0x00, 0x40), (SCR, 0x02, 0), (SCR, 0x06, SCR), (SCR, 0x08, 0)]

# gm @0xA00 with 1 loop ("m.l") + 1 sound ("s.snd", no voc)
_GMS = [(SCR, 0xA00 + 0x38, 1),
        (SCR, 0xA00 + 0x3A, 0x0500), (SCR, 0xA00 + 0x3C, SCR),
        (SCR, 0xA00 + 0x39, 1),
        (SCR, 0xA00 + 0x292, 0x0700), (SCR, 0xA00 + 0x294, SCR),
        (SCR, 0xA00 + 0x1C, 0),
        ("dg", _DG_GAME + 0, 0x0A00), ("dg", _DG_GAME + 2, SCR),
        ("dg", _DG_CSND + 0, 0), ("dg", _DG_CSND + 2, 0),
        ("dg", _DG_CAST + 0, 0x0B00), ("dg", _DG_CAST + 2, SCR),
        (SCR, 0x0B00, 0)]

_LOOP_ML = [(SCR, 0x500 + 0, 4),
            (SCR, 0x500 + 2, 0x0680), (SCR, 0x500 + 4, SCR),
            (SCR, 0x500 + 6, 0x0600), (SCR, 0x500 + 8, SCR),
            (SCR, 0x600 + 4, 8), (SCR, 0x600 + 6, 8),
            (SCR, 0x680, 0x2E6D), (SCR, 0x682, 0x006C),     # "m.l\0"
            (SCR, 0x690, 0x2E73), (SCR, 0x692, 0x6E73),
            (SCR, 0x694, 0x646E), (SCR, 0x696, 0x0000),     # "s.snd\0"
            (SCR, 0x700 + 0, 0x0690), (SCR, 0x700 + 2, SCR),  # snd name
            (SCR, 0x700 + 4, 0), (SCR, 0x700 + 6, 1)]          # pri=0,has data

def _msl_rec(i, snd=0x0690, lname=0x0680, rname=0x0680,
             v0=9, v1=6, v2=2, link=0x0800, flag=1):
    b = _MSL_BASE + i * 0x16
    return [("dg", b + 0x00, snd), ("dg", b + 0x02, SCR),
            ("dg", b + 0x04, lname), ("dg", b + 0x06, SCR),
            ("dg", b + 0x08, rname), ("dg", b + 0x0A, SCR),
            ("dg", b + 0x0C, v0 | (v1 << 8)),
            ("dg", b + 0x0E, v2),
            ("dg", b + 0x10, link), ("dg", b + 0x12, SCR),
            ("dg", b + 0x14, flag)]

# shooter @0x200: in_window, face param
def _shooter(face=0, inwin=2, x=100, y=50, extra=()):
    return [(SCR, 0x0200 + 0x00, x), (SCR, 0x0200 + 0x02, y),
            (SCR, 0x0200 + 0x10, 8), (SCR, 0x0200 + 0x12, 8),
            (SCR, 0x0200 + 0x0A, y + 4), (SCR, 0x0200 + 0x04, x + 8),
            (SCR, 0x0200 + 0x34, face), (SCR, 0x0200 + 0x52, inwin)] + list(extra)

# actor window skips +0x3E..+0x45 (doit/moveit fn ptrs — code offsets differ)
_MSL_WIN = [(ACT_SEG, ACT_OFF + 0x00, 0x3E), (ACT_SEG, ACT_OFF + 0x46, 0x0E),
            (SCR, 0x0B00, 6)]

_AM_BASE = _GMS + _LOOP_ML + _HEAP + _msl_rec(0) + MAP_POKES[:2] + _VIEW \
         + [("dg", _DG_EDSZ, 0)]

TESTS += [
    # face=0 -> spr_l; x=own.x-act.w; x_step=-1; y=cy+3
    Test("msl_left", ("seg03f9", 0x33C9), "add_missile(m_actor far*,unsigned char,int)",
         args=[0x0200, SCR, 0, 0],
         pokes=_AM_BASE + _shooter(face=0),
         windows=_MSL_WIN),
    # face=1 -> spr_r; x=own.xw-3; x_step=+1
    Test("msl_right", ("seg03f9", 0x33C9), "add_missile(m_actor far*,unsigned char,int)",
         args=[0x0200, SCR, 0, 0],
         pokes=_AM_BASE + _shooter(face=1),
         windows=_MSL_WIN),
    # dir!=0 -> y=own.y+dir
    Test("msl_dir4", ("seg03f9", 0x33C9), "add_missile(m_actor far*,unsigned char,int)",
         args=[0x0200, SCR, 0, 4],
         pokes=_AM_BASE + _shooter(face=0),
         windows=_MSL_WIN),
    # type=9 -> act+0x3D=3, +0x16=-7
    Test("msl_type9", ("seg03f9", 0x33C9), "add_missile(m_actor far*,unsigned char,int)",
         args=[0x0200, SCR, 9, 0],
         pokes=_AM_BASE + _shooter(face=0) + _msl_rec(9),
         windows=_MSL_WIN),
    # not in_window -> early out (cast stays empty)
    Test("msl_nowin", ("seg03f9", 0x33C9), "add_missile(m_actor far*,unsigned char,int)",
         args=[0x0200, SCR, 0, 0],
         pokes=_AM_BASE + _shooter(face=0, inwin=0),
         windows=_MSL_WIN),
]

# ego_fire: ego@0x200 shooter; jason@0x300 standby.
# recs 0..5 all resolvable (shot_size/heavy/jason paths index different recs).
_EF_RECS = [p for i in range(6) for p in _msl_rec(i)]
_EF_G = _AM_BASE + _shooter(face=0) + _EF_RECS \
      + [("dg", _DG_JON, 0), ("dg", _DG_JPRES, 0),
         ("dg", _DG_EGO + 0, 0x0200), ("dg", _DG_EGO + 2, SCR),
         ("dg", _DG_JASON + 0, 0x0300), ("dg", _DG_JASON + 2, SCR),
         ("dg", _DG_SHCNT, 0), ("dg", _DG_SHSZ, 0), ("dg", _DG_TOPCNT, 0),
         ("dg", _DG_HVY, 0), ("dg", _DG_JFIRE, 0), ("dg", _DG_TFIRE, 0)]

_EF_WIN = [(ACT_SEG, ACT_OFF + 0x00, 0x3E), (ACT_SEG, ACT_OFF + 0x46, 0x0E),
           (SCR, 0x0B00, 6), ("dg", _DG_SHCNT, 4), ("dg", _DG_HVY, 2)]

TESTS += [
    Test("ef_basic", ("seg03f9", 0x3A2D), "ego_fire()",
         pokes=_EF_G + [(SCR, 0x0200 + 0x3D, 0)],
         windows=_EF_WIN),
    Test("ef_max", ("seg03f9", 0x3A2D), "ego_fire()",
         pokes=_EF_G + [(SCR, 0x0200 + 0x3D, 0), ("dg", _DG_SHCNT, 5)],
         windows=_EF_WIN),
    # ego turning (+0x3D==1) -> no shot
    Test("ef_turning", ("seg03f9", 0x3A2D), "ego_fire()",
         pokes=_EF_G + [(SCR, 0x0200 + 0x3D, 1)],
         windows=_EF_WIN),
    # shot_size=2 -> recoil: face=0 -> x_step -= (2+2)
    Test("ef_recoil", ("seg03f9", 0x3A2D), "ego_fire()",
         pokes=_EF_G + [(SCR, 0x0200 + 0x3D, 0), (SCR, 0x0200 + 0x14, 2),
                        ("dg", _DG_SHSZ, 2)],
         windows=_EF_WIN + [(SCR, 0x0200 + 0x14, 2)]),
    # jason_on -> jason fires (arg6=4 path)
    Test("ef_jason", ("seg03f9", 0x3A2D), "ego_fire()",
         pokes=_EF_G + [("dg", _DG_JON, 1), ("dg", _DG_JPRES, 1),
                        (SCR, 0x0300 + 0x00, 100), (SCR, 0x0300 + 0x02, 50),
                        (SCR, 0x0300 + 0x04, 108), (SCR, 0x0300 + 0x10, 8),
                        (SCR, 0x0300 + 0x12, 8), (SCR, 0x0300 + 0x0A, 54),
                        (SCR, 0x0300 + 0x34, 1), (SCR, 0x0300 + 0x52, 2),
                        (SCR, 0x0300 + 0x3D, 0)],
         windows=_EF_WIN),
]

# ---------------------------------------------------------------------------
# do_missle(act) — per-frame missile update. seg0b2c:352C.
#
# Branches:
#   !in_window -> dead (no explosion)
#   face==1: x_step -= 2 while > -max_speed; face==0: x_step += 2 while < max
#   +0x3D==3 (type9): y_step++ until 10
#   +0x52 bit7: random(10)==0 -> add_bubble
#   owner(+0x2C)+0x35 & 0x10 (player-owned):
#       scan _shootable_list[0.._shootable_count): skip dead(bit5),
#       touching -> target+0x52|=8, +0x28 += energy(+0x26), +0x1E=+-5 knockback,
#       +0x35 bit5 target: +0x52|=0x40 when hit within h/2 vertically,
#       energy<10 -> dead else pierce;
#       +0x34=='c' (top): tile[+0x18]==0x100 -> dead; else y_step-- toward -max
#   else (enemy-owned):
#       _smart_missiles==1 && +0x34!=0x63: y_step = sign(cur_sub.cy - act.cy)
#       scan _barrier_list: touching -> dead
#       touching(_cur_sub) -> hit_cur_sub(energy, +-5), aux=link, dead
#   energy<10 && tile_collision(0,0,0) -> dead
#   dead: +0x52|=1; 'c' -> _top_shot_count--; owner+0x35&0x10 -> _shot_count--;
#         if in_window: add_explosion(cx,cy,+0x22, hit_sub? link : NULL)
#
# Globals: _cur_sub@34B4, _act@34A4, _shootable_count@351D,
#   _shootable_list[]@35B6, _barrier_count@351C, _barrier_list[]@352A,
#   _shot_count@34CF, _top_shot_count@34D1, _smart_missiles@34DE,
#   _diff_y@3658, _all_explosions@01F4 (8B recs: +0 spr,+4 snd names).
# ---------------------------------------------------------------------------

_DG_SCNT  = 0x351D
_DG_SLIST = 0x35B6
_DG_SMART = 0x34DE
_DG_DIFFY = 0x3658
_EXP_BASE = 0x01F4

_EXP_RECS = [p for i in range(6) for p in
             [("dg", _EXP_BASE + i * 8 + 0, 0x0680),
              ("dg", _EXP_BASE + i * 8 + 2, SCR),
              ("dg", _EXP_BASE + i * 8 + 4, 0x0690),
              ("dg", _EXP_BASE + i * 8 + 6, SCR)]]

# pixel chain for the "other" actor @0x200 (loopres@0x540 cel@0x6A0 bmp@0x790)
_PX2 = [(SCR, 0x0540 + 6, 0x06A0), (SCR, 0x0540 + 8, SCR),
        (SCR, 0x06A0 + 0, 0x0790), (SCR, 0x06A0 + 2, SCR)]
# missile pixel chain: _LOOP_ML loopres@0x500 cel0@0x600 -> bmp@0x750
_PX1 = [(SCR, 0x0600 + 0, 0x0750), (SCR, 0x0600 + 2, SCR)]
# overlap bytes for A@(16,8) vs B@(23,15)
_PXB = [(SCR, 0x750 + 56, 0x0101), (SCR, 0x750 + 58, 0x0101),
        (SCR, 0x750 + 60, 0x0101), (SCR, 0x750 + 62, 0x0101),
        (SCR, 0x790 + 0, 0x0101), (SCR, 0x790 + 2, 0x0101),
        (SCR, 0x790 + 4, 0x0101), (SCR, 0x790 + 6, 0x0101)]

def _dm_msl(x=16, y=8, xs=0, ys=0, mspd=6, en=9, face=0, owner=0x0440,
            mode=0, tileidx=10, inwin=2, exp=0, link=0, wt=2, ht=2, flags=0):
    return [(SCR, 0x0400 + 0x00, x), (SCR, 0x0400 + 0x02, y),
            (SCR, 0x0400 + 0x04, x + 8), (SCR, 0x0400 + 0x06, y + 8),
            (SCR, 0x0400 + 0x08, x + 4), (SCR, 0x0400 + 0x0A, y + 4),
            (SCR, 0x0400 + 0x10, 8), (SCR, 0x0400 + 0x12, 8),
            (SCR, 0x0400 + 0x14, xs & 0xFFFF), (SCR, 0x0400 + 0x16, ys & 0xFFFF),
            (SCR, 0x0400 + 0x18, tileidx), (SCR, 0x0400 + 0x1A, wt),
            (SCR, 0x0400 + 0x1C, ht), (SCR, 0x0400 + 0x22, exp),
            (SCR, 0x0400 + 0x24, mspd), (SCR, 0x0400 + 0x26, en),
            (SCR, 0x0400 + 0x2C, owner), (SCR, 0x0400 + 0x2E, SCR),
            (SCR, 0x0400 + 0x34, face), (SCR, 0x0400 + 0x3C, 0),
            (SCR, 0x0400 + 0x3D, mode), (SCR, 0x0400 + 0x46, 0x0500),
            (SCR, 0x0400 + 0x48, SCR), (SCR, 0x0400 + 0x4E, link),
            (SCR, 0x0400 + 0x50, SCR if link else 0),
            (SCR, 0x0400 + 0x52, inwin | flags)]

def _dm_actor(off, x=23, y=15, fl35=0x10, flags=0, dead=0, w=8, h=8):
    return [(SCR, off + 0x00, x), (SCR, off + 0x02, y),
            (SCR, off + 0x04, x + w), (SCR, off + 0x06, y + h),
            (SCR, off + 0x08, x + w // 2), (SCR, off + 0x0A, y + h // 2),
            (SCR, off + 0x10, w), (SCR, off + 0x12, h),
            (SCR, off + 0x35, fl35), (SCR, off + 0x3C, 0),
            (SCR, off + 0x46, 0x0540), (SCR, off + 0x48, SCR),
            (SCR, off + 0x52, flags | (dead << 5))]

_DM_G = _GMS + _LOOP_ML + _HEAP + _EXP_RECS + MAP_POKES + _VIEW + TILE_FREE \
      + _PX1 + [("dg", _DG_EDSZ, 0), ("dg", _DG_SCNT, 0),
                ("dg", _DG_BCNT, 0), ("dg", _DG_SMART, 0),
                ("dg", _DG_SHCNT, 3), ("dg", _DG_TOPCNT, 1),
                ("dg", _DG_CURSUB + 0, 0x0480), ("dg", _DG_CURSUB + 2, SCR),
                (SCR, 0x0440 + 0x35, 0x10),   # owner = player-owned default
                (SCR, 0x0480 + 0x0A, 60)]   # cur_sub cy

_MSL_ARG = [0x0400, SCR]
_DM_WIN = [(SCR, 0x0400, 0x3E), (SCR, 0x0400 + 0x46, 0x0E)]

TESTS += [
    Test("dm_accel_l", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG, pokes=_DM_G + _dm_msl(face=0, xs=0),
         windows=_DM_WIN),
    Test("dm_accel_r", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG, pokes=_DM_G + _dm_msl(face=1, xs=0),
         windows=_DM_WIN),
    Test("dm_accel_cap", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG, pokes=_DM_G + _dm_msl(face=0, xs=6),
         windows=_DM_WIN),
    Test("dm_t9", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG, pokes=_DM_G + _dm_msl(mode=3, ys=5),
         windows=_DM_WIN),
    Test("dm_t9_cap", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG, pokes=_DM_G + _dm_msl(mode=3, ys=10),
         windows=_DM_WIN),
    # player missile hits shootable target -> dmg/knock/hit-flag, msl dies
    Test("dm_hit", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1) + _dm_actor(0x0200, 23, 15) + _PX2 + _PXB
              + [("dg", _DG_SCNT, 1),
                 ("dg", _DG_SLIST + 0, 0x0200), ("dg", _DG_SLIST + 2, SCR)],
         windows=_DM_WIN + [(SCR, 0x0200, 0x54), ("dg", _DG_SHCNT, 4),
                            (ACT_SEG, ACT_OFF, 0x3E)]),
    # dead-flagged target skipped -> missile survives, continues
    Test("dm_hit_dead", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1) + _dm_actor(0x0200, 23, 15, dead=1)
              + _PX2 + _PXB
              + [("dg", _DG_SCNT, 1),
                 ("dg", _DG_SLIST + 0, 0x0200), ("dg", _DG_SLIST + 2, SCR)],
         windows=_DM_WIN + [(SCR, 0x0200, 0x54), ("dg", _DG_SHCNT, 4)]),
    # energy>=10 -> pierce: missile survives the hit
    Test("dm_pierce", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, en=10) + _dm_actor(0x0200, 23, 15)
              + _PX2 + _PXB
              + [("dg", _DG_SCNT, 1),
                 ("dg", _DG_SLIST + 0, 0x0200), ("dg", _DG_SLIST + 2, SCR)],
         windows=_DM_WIN + [(SCR, 0x0200, 0x54), ("dg", _DG_SHCNT, 4)]),
    # enemy missile hits cur_sub -> hit_cur_sub + dead + explosion(link snd)
    Test("dm_hit_sub", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, owner=0x0440, link=0x0690)
              + _dm_actor(0x0480, 23, 15, fl35=0x10)       # cur_sub
              + _PX2 + _PXB
              + [("dg", _DG_CURSUB + 0, 0x0480), ("dg", _DG_CURSUB + 2, SCR)]
              + [(SCR, 0x0440 + 0x35, 0)],                 # owner+0x35=0
         windows=_DM_WIN + [(SCR, 0x0480, 0x54), ("dg", _DG_SHCNT, 4),
                            (ACT_SEG, ACT_OFF, 0x3E)]),
    # enemy missile touching barrier -> dead
    Test("dm_barrier", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, owner=0x0440)
              + _dm_actor(0x0200, 23, 15, fl35=0)          # barrier
              + [(SCR, 0x0440 + 0x35, 0)]
              + _PX2 + _PXB
              + [("dg", _DG_BCNT, 1),
                 ("dg", _DG_BLIST + 0, 0x0200), ("dg", _DG_BLIST + 2, SCR)],
         windows=_DM_WIN + [("dg", _DG_SHCNT, 4)]),
    # enemy missile, barrier far -> survives to tile check
    Test("dm_barrier_miss", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, owner=0x0440)
              + _dm_actor(0x0200, 200, 100, fl35=0)        # far barrier
              + [(SCR, 0x0440 + 0x35, 0)]
              + [("dg", _DG_BCNT, 1),
                 ("dg", _DG_BLIST + 0, 0x0200), ("dg", _DG_BLIST + 2, SCR)],
         windows=_DM_WIN),
    # player missile + wall tile + energy<10 -> dead
    Test("dm_tile", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1)
              + [(SCR, 0x800 + 10 * 4, 0x0001)],
         windows=_DM_WIN + [("dg", _DG_SHCNT, 4), (ACT_SEG, ACT_OFF, 0x3E)]),
    # energy>=10 -> tile check skipped entirely
    Test("dm_tile_hi", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, en=10)
              + [(SCR, 0x800 + 10 * 4, 0x0001)],
         windows=_DM_WIN),
    # off-screen -> dead, shot_count--, no explosion
    Test("dm_offscreen", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG, pokes=_DM_G + _dm_msl(xs=1, inwin=0),
         windows=_DM_WIN + [("dg", _DG_SHCNT, 4)]),
    # top shot: y_step accelerates toward -max_speed
    Test("dm_top", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(face=0x63, ys=-3, en=10),
         windows=_DM_WIN),
    # top shot on solid tile -> dead, top_shot_count--
    Test("dm_top_wall", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(face=0x63, ys=-3, en=10, tileidx=10)
              + [(SCR, 0x800 + 10 * 4, 0x0100)],
         windows=_DM_WIN + [("dg", _DG_TOPCNT, 2), (ACT_SEG, ACT_OFF, 0x3E)]),
    # smart missile steering (enemy-owned): cy below/above/equal cur_sub
    Test("dm_smart_up", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, owner=0x0440, en=10)
              + [(SCR, 0x0400 + 0x0A, 80), (SCR, 0x0440 + 0x35, 0),
                 ("dg", _DG_SMART, 1)],
         windows=_DM_WIN),
    Test("dm_smart_dn", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, owner=0x0440, en=10)
              + [(SCR, 0x0400 + 0x0A, 40), (SCR, 0x0440 + 0x35, 0),
                 ("dg", _DG_SMART, 1)],
         windows=_DM_WIN),
    Test("dm_smart_eq", ("seg0b2c", 0x352C), "do_missle(m_actor far*)",
         args=_MSL_ARG,
         pokes=_DM_G + _dm_msl(xs=1, owner=0x0440, en=10)
              + [(SCR, 0x0400 + 0x0A, 60), (SCR, 0x0440 + 0x35, 0),
                 ("dg", _DG_SMART, 1)],
         windows=_DM_WIN),
]

# ---------------------------------------------------------------------------
# game_cast::update(flag) — seg1224:0FBD. Cast obj: +0 count byte, +2 items.
#   flag==0: ego->erase() + erase each ed_list actor
#   flag!=0: clear +0x52 bits 0x10|0x04 on each ed_list actor
#   _ed_list_size = 0
#   for i < count: if items[i]+0x52 & 1 -> remove(i)   (i++ still runs —
#     consecutive dead actors are SKIPPED: remove shifts list left)
#   cycle+move all actors: (count>>4)x16 unrolled + remainder
#   ego->draw() + draw each (new) ed_list actor
# remove(i): ~m_actor(3) [frees block at item seg], my_movsd shift, count--
# Globals: _ego@34A8, _ed_list@366A, _ed_list_size@37FA
# ---------------------------------------------------------------------------

# cast @0xB00; actors @0x0C00+i*0x60 (outside heap block); ego@0x1300
def _up_actor(off, x=2000, y=2000, xs=0, ys=0, flags=0, cycler=0):
    return [(SCR, off + 0x00, x), (SCR, off + 0x02, y),
            (SCR, off + 0x04, x + 8), (SCR, off + 0x06, y + 8),
            (SCR, off + 0x08, x + 4), (SCR, off + 0x0A, y + 4),
            (SCR, off + 0x10, 8), (SCR, off + 0x12, 8),
            (SCR, off + 0x14, xs & 0xFFFF), (SCR, off + 0x16, ys & 0xFFFF),
            (SCR, off + 0x18, 0), (SCR, off + 0x1A, 1), (SCR, off + 0x1C, 1),
            (SCR, off + 0x22, 0), (SCR, off + 0x34, 0),
            (SCR, off + 0x38, cycler), (SCR, off + 0x39, 0),
            (SCR, off + 0x3A, 1), (SCR, off + 0x3B, 2), (SCR, off + 0x3C, 0),
            (SCR, off + 0x3D, 0),
            (SCR, off + 0x46, 0x0500), (SCR, off + 0x48, SCR),
            (SCR, off + 0x52, flags)]

def _cast(cnt, offs):
    p = [(SCR, 0x0B00, cnt)]
    for i, o in enumerate(offs):
        p += [(SCR, 0x0B02 + i * 4, o), (SCR, 0x0B04 + i * 4, SCR)]
    return p

_UP_G = _GMS + _LOOP_ML + _HEAP + MAP_POKES + _VIEW + _PX1 \
      + [("dg", _DG_EDSZ, 0), ("dg", _DG_EGO + 0, 0x1300),
         ("dg", _DG_EGO + 2, SCR)]

_UP_A = lambda i: 0x0C00 + i * 0x60
_CST_WIN = [(SCR, 0x0B00, 0x46), ("dg", _DG_EDSZ, 2), ("dg", _DG_EDLIST, 8),
            ("sym:___rover", 0, 2), (SCR, 0x00, 8)]

TESTS += [
    Test("upd_empty", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 1], pokes=_UP_G + _cast(0, []) + _up_actor(0x1300),
         windows=_CST_WIN),
    Test("upd_alive", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 1],
         pokes=_UP_G + _cast(2, [_UP_A(0), _UP_A(1)])
              + _up_actor(_UP_A(0), xs=1) + _up_actor(_UP_A(1), ys=-1)
              + _up_actor(0x1300),
         windows=_CST_WIN + [(SCR, _UP_A(0), 0x54), (SCR, _UP_A(1), 0x54)]),
    # idx1 dead -> remove(1): destructor frees block, movsd shifts, count=2
    Test("upd_dead", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 1],
         pokes=_UP_G + _cast(3, [_UP_A(0), _UP_A(1), _UP_A(2)])
              + _up_actor(_UP_A(0)) + _up_actor(_UP_A(1), flags=1)
              + _up_actor(_UP_A(2)) + _up_actor(0x1300),
         windows=_CST_WIN + [(SCR, _UP_A(0), 0x54), (SCR, _UP_A(1), 0x54),
                             (SCR, _UP_A(2), 0x54)]),
    # consecutive dead: remove(0) shifts; i++ skips new[0] -> dead stays
    Test("upd_dead2", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 1],
         pokes=_UP_G + _cast(3, [_UP_A(0), _UP_A(1), _UP_A(2)])
              + _up_actor(_UP_A(0), flags=1) + _up_actor(_UP_A(1), flags=1)
              + _up_actor(_UP_A(2)) + _up_actor(0x1300),
         windows=_CST_WIN + [(SCR, _UP_A(0), 0x54), (SCR, _UP_A(1), 0x54),
                             (SCR, _UP_A(2), 0x54)]),
    # flag=0 -> erase path (all out-of-window -> no-ops) then same flow
    Test("upd_flag0", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 0],
         pokes=_UP_G + _cast(2, [_UP_A(0), _UP_A(1)])
              + _up_actor(_UP_A(0)) + _up_actor(_UP_A(1)) + _up_actor(0x1300)
              + [("dg", _DG_EDSZ, 1),
                 ("dg", _DG_EDLIST + 0, _UP_A(0)), ("dg", _DG_EDLIST + 2, SCR)],
         windows=_CST_WIN + [(SCR, _UP_A(0), 0x54), (SCR, _UP_A(1), 0x54)]),
    # flag=1 -> clear ed_list actors' bits 0x10|0x04, ed_list_size=0
    Test("upd_flagclr", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 1],
         pokes=_UP_G + _cast(1, [_UP_A(2)])
              + _up_actor(_UP_A(0), flags=0x14) + _up_actor(_UP_A(2))
              + _up_actor(0x1300)
              + [("dg", _DG_EDSZ, 1),
                 ("dg", _DG_EDLIST + 0, _UP_A(0)), ("dg", _DG_EDLIST + 2, SCR)],
         windows=_CST_WIN + [(SCR, _UP_A(0), 0x54), (SCR, _UP_A(2), 0x54)]),
    # 17 actors -> 16-unrolled group + remainder path
    Test("upd_17", ("seg1224", 0x0FBD), "game_cast::update(unsigned char)",
         args=[0x0B00, SCR, 1],
         pokes=_UP_G + _cast(17, [_UP_A(i) for i in range(17)])
              + [p for i in range(17)
                 for p in _up_actor(_UP_A(i), xs=1)]
              + _up_actor(0x1300),
         windows=_CST_WIN + [(SCR, _UP_A(i), 0x54) for i in range(17)]),
]


def main():
    verbose = "-v" in sys.argv
    run_all = "--all" in sys.argv          # ignore proven registry, run everything
    only = [a for a in sys.argv[1:] if a not in ("-v", "--all")]
    proven_names = set() if run_all else load_proven_names()
    proven_linears = set() if run_all else load_proven_linears()
    proven_exe = {} if run_all else load_proven_exe()
    npass = nfail = nproven = 0
    for t in TESTS:
        if only and not any(o in t.name for o in only):
            continue
        hits = _orig_names_for_test(t) & proven_names
        linear = _orig_linear_for_test(t)
        hit_linear = linear is not None and linear in proven_linears
        if hits or hit_linear:
            if hit_linear and not _proven_still_valid(linear, proven_exe):
                print(f"STALE {t.name}: z3 proof exists but machine code changed — retesting")
            else:
                nproven += 1
                if verbose:
                    label = sorted(hits)[0] if hits else f"linear 0x{linear:05x}"
                    print(f"PROVEN {t.name}: z3-verified ({label})")
                continue
        try:
            ok = run_test(t, verbose)
        except KeyError as e:
            print(f"SKIP {t.name}: unresolved {e}")
            continue
        npass += bool(ok)
        nfail += not ok
    print(f"\n{npass} pass/warn, {nfail} diff, {nproven} z3-proven skipped")


if __name__ == "__main__":
    main()
